load("config.js");

function execute() {
  return Response.success([
    { title: "Tất cả Anime", input: "/vi/category?season_type=1,4", script: "homecontent.js" },
    { title: "Tác phẩm gốc", input: "/vi/category?style_id=20001&season_type=1,4", script: "homecontent.js" },
    { title: "Truyện tranh chuyển thể", input: "/vi/category?style_id=20002&season_type=1,4", script: "homecontent.js" },
    { title: "Tiểu thuyết chuyển thể", input: "/vi/category?style_id=20003&season_type=1,4", script: "homecontent.js" },
    { title: "Game chuyển thể", input: "/vi/category?style_id=20004&season_type=1,4", script: "homecontent.js" },
    { title: "Tokusatsu", input: "/vi/category?style_id=20005&season_type=1,4", script: "homecontent.js" },
    { title: "Nhiệt huyết", input: "/vi/category?style_id=20006&season_type=1,4", script: "homecontent.js" },
    { title: "Dị giới", input: "/vi/category?style_id=20007&season_type=1,4", script: "homecontent.js" },
    { title: "Siêu năng lực", input: "/vi/category?style_id=20008&season_type=1,4", script: "homecontent.js" },
    { title: "Xuyên không", input: "/vi/category?style_id=20009&season_type=1,4", script: "homecontent.js" },
    { title: "Giả tưởng", input: "/vi/category?style_id=20010&season_type=1,4", script: "homecontent.js" },
    { title: "Hành động", input: "/vi/category?style_id=20011&season_type=1,4", script: "homecontent.js" },
    { title: "Hài", input: "/vi/category?style_id=20012&season_type=1,4", script: "homecontent.js" },
    { title: "Đời thường", input: "/vi/category?style_id=20013&season_type=1,4", script: "homecontent.js" },
    { title: "Khoa học viễn tưởng", input: "/vi/category?style_id=20014&season_type=1,4", script: "homecontent.js" },
    { title: "Moe", input: "/vi/category?style_id=20015&season_type=1,4", script: "homecontent.js" },
    { title: "Chữa lành", input: "/vi/category?style_id=20016&season_type=1,4", script: "homecontent.js" },
    { title: "Vườn trường", input: "/vi/category?style_id=20017&season_type=1,4", script: "homecontent.js" },
    { title: "Thiếu nhi", input: "/vi/category?style_id=20018&season_type=1,4", script: "homecontent.js" },
    { title: "Tình yêu", input: "/vi/category?style_id=20019&season_type=1,4", script: "homecontent.js" },
    { title: "Thiếu nữ", input: "/vi/category?style_id=20020&season_type=1,4", script: "homecontent.js" },
    { title: "Phiêu lưu", input: "/vi/category?style_id=20021&season_type=1,4", script: "homecontent.js" },
    { title: "Lịch sử", input: "/vi/category?style_id=20022&season_type=1,4", script: "homecontent.js" },
    { title: "Mecha", input: "/vi/category?style_id=20023&season_type=1,4", script: "homecontent.js" },
    { title: "Thể thao", input: "/vi/category?style_id=20024&season_type=1,4", script: "homecontent.js" },
    { title: "Truyền cảm hứng", input: "/vi/category?style_id=20025&season_type=1,4", script: "homecontent.js" },
    { title: "Âm nhạc", input: "/vi/category?style_id=20026&season_type=1,4", script: "homecontent.js" },
    { title: "Thần bí", input: "/vi/category?style_id=20027&season_type=1,4", script: "homecontent.js" },
    { title: "Thần tượng", input: "/vi/category?style_id=20028&season_type=1,4", script: "homecontent.js" },
    { title: "Công sở", input: "/vi/category?style_id=20029&season_type=1,4", script: "homecontent.js" },
    { title: "Ẩm thực", input: "/vi/category?style_id=20030&season_type=1,4", script: "homecontent.js" },
    { title: "Cổ trang", input: "/vi/category?style_id=20031&season_type=1,4", script: "homecontent.js" },
    { title: "Huyền huyễn", input: "/vi/category?style_id=20032&season_type=1,4", script: "homecontent.js" },
    { title: "Tu tiên", input: "/vi/category?style_id=20033&season_type=1,4", script: "homecontent.js" },
    { title: "Phục thù", input: "/vi/category?style_id=20034&season_type=1,4", script: "homecontent.js" },
    { title: "Suy luận", input: "/vi/category?style_id=20035&season_type=1,4", script: "homecontent.js" },
    { title: "Cảm động", input: "/vi/category?style_id=20036&season_type=1,4", script: "homecontent.js" },
    { title: "Kiếm hiệp", input: "/vi/category?style_id=20037&season_type=1,4", script: "homecontent.js" },
    { title: "Hậu cung", input: "/vi/category?style_id=20038&season_type=1,4", script: "homecontent.js" },
    { title: "Furry", input: "/vi/category?style_id=20039&season_type=1,4", script: "homecontent.js" },
    { title: "18+", input: "/vi/category?style_id=20040&season_type=1,4", script: "homecontent.js" },
    { title: "Đam mỹ", input: "/vi/category?style_id=20041&season_type=1,4", script: "homecontent.js" },
    { title: "Bách hợp", input: "/vi/category?style_id=20042&season_type=1,4", script: "homecontent.js" },
    { title: "Thành thị", input: "/vi/category?style_id=20043&season_type=1,4", script: "homecontent.js" },
    { title: "Thi đấu", input: "/vi/category?style_id=20044&season_type=1,4", script: "homecontent.js" },
    { title: "Hiện đại", input: "/vi/category?style_id=20045&season_type=1,4", script: "homecontent.js" },
    { title: "Truyện", input: "/vi/category?style_id=20046&season_type=1,4", script: "homecontent.js" }
  ]);
}
