var nameDict = [
    ["っ", "っ"],
    ["づ", "づ"],
    ["ど", "ど"],
    ["へ", "へ"],
    ["ノ", "ノ"],
    ["ミ", "ミ"],
    ["メ", "メ"],
    ["ロ", "ロ"],
    ["ㅂ", "ㅂ"],
    ["ㅍ", "ㅍ"],
    ["冯", "Bon"],
    ["凯", "Gai"],
    ["凸", "凸"],
    ["劫", "Zed"],
    ["彡", "彡"],
    ["影", "Ei (ảnh)"],
    ["忍", "Shinobu"],
    ["扳", "ban"],
    ["斑", "ban(Madara)"],
    ["晓", "hiểu*(Akatsuki)"],
    ["柊", "Hiiragi"],
    ["根", "Root"],
    ["楔", "tiết(Karma)"],
    ["烬", "Jhin"],
    ["熊", "Kuma"],
    ["牛", "Alistar"],
    ["琳", "Lynn"],
    ["琴", "Jean"],
    ["白", "bạch*(Haku)"],
    ["皿", "皿"],
    ["空", "Aether (không)"],
    ["红", "hồng(Kurenai)"],
    ["艾", "A"],
    ["苯", "benzene"],
    ["荧", "Lumine"],
    ["蔚", "Vi"],
    ["蝎", "bọ cạp(Sasori)"],
    ["酱", "- chan"],
    ["钚", "plutonium"],
    ["铀", "uranium"],
    ["霞", "Xayah"],
    ["青", "thanh(Ao)"],
    ["鵺", "Nue"],
    ["鹤", "Tsuru"],
    ["鼬", "Itachi"],
    ["一乐", "Ichikaru"],
    ["一代", "Đệ Nhất"],
    ["一式", "Isshiki"],
    ["一笑", "Isshō (mỉm cười)"],
    ["丁次", "Chōji"],
    ["七代", "Đệ Thất"],
    ["七神", "Thất Tinh"],
    ["万刀", "vạn USD"],
    ["万国", "Totto Land"],
    ["万科", "Vanko"],
    ["三代", "Đệ Tam"],
    ["三忍", "Sannin"],
    ["三船", "Mifune"],
    ["三郎", "Saburo"],
    ["上帝", "God"],
    ["上忍", "thượng nhẫn"],
    ["下忍", "hạ nhẫn"],
    ["下毒", "hạ độc"],
    ["丑角", "The Jester"],
    ["丘丘", "Hilichurl"],
    ["东瀛", "Japan"],
    ["丧鞭", "Whiplash"],
    ["中二", "chūnibyō"],
    ["中心", "trung tâm"],
    ["中忍", "trung nhẫn"],
    ["串丸", "Kushimaru"],
    ["丸星", "Maruboshi"],
    ["丹特", "Dent"],
    ["主持", "chủ trì"],
    ["主神", "Chủ thần"],
    ["丽萨", "Lisa"],
    ["义警", "Vigilante"],
    ["乌冬", "Udon"],
    ["乌塔", "Uta"],
    ["乌萨", "Ursa"],
    ["乌鲁", "Uru"],
    ["乌龟", "Rammus"],
    ["乔特", "Shotto"],
    ["乔迁", "dời đến chỗ ở tốt"],
    ["九尾", "Cửu Vĩ"],
    ["九条", "Kujou"],
    ["九里", "Kuri"],
    ["二代", "Đệ Nhị"],
    ["二挡", "Gear 2"],
    ["二桶", "Đệ nhị Robin"],
    ["云忍", "ninja Làng Mây"],
    ["云来", "Vân Lai"],
    ["云董", "Yunjin"],
    ["五代", "Đệ Ngũ"],
    ["井野", "Ino"],
    ["井阵", "Inojin"],
    ["亚卡", "Yaka"],
    ["亡刃", "Corvus Glaive"],
    ["亡灵", "Sion"],
    ["亥一", "Inoichi"],
    ["人偶", "Marionette (con rối)"],
    ["人格", "nhân cách"],
    ["人类", "nhân loại"],
    ["人马", "Hecarim"],
    ["仆人", "The Knave (người hầu)"],
    ["从魔", "Slave"],
    ["仙贝", "donut"],
    ["代蒙", "Daemon"],
    ["以太", "Aether"],
    ["以藏", "Izou"],
    ["伊万", "Ivan"],
    ["伊仓", "Ikura"],
    ["伊势", "Ise"],
    ["伊孔", "Ikonn"],
    ["伊度", "Eduardo"],
    ["伊本", "Ibn"],
    ["伊法", "Ifa"],
    ["伊述", "Isu"],
    ["伍德", "Woodrue"],
    ["优拉", "Eula"],
    ["伙计", "Buddy"],
    ["传授", "truyền thụ"],
    ["传送", "Dịch Chuyển"],
    ["伲卡", "Nika"],
    ["位格", "vị cách"],
    ["佐伯", "Zola"],
    ["佐助", "Sasuke"],
    ["佐拉", "Zola"],
    ["佑介", "Yusuke"],
    ["佛瑞", "Furry"],
    ["作业", "bài tập"],
    ["佩奇", "Pegg"],
    ["佩波", "Pepper"],
    ["佩珀", "Pepper"],
    ["佩金", "Penguin"],
    ["保尔", "Bórr"],
    ["保险", "bảo hiểm"],
    ["信仰", "tín ngưỡng"],
    ["信奉", "thờ phụng"],
    ["信玄", "Shingen"],
    ["修佐", "Shusuke"],
    ["借风", "Tá Phong"],
    ["僕人", "The Knave (người hầu)"],
    ["光代", "Teruyo"],
    ["光头", "Ryze"],
    ["光月", "Kouzuki"],
    ["克劳", "Klaw"],
    ["克里", "Kree"],
    ["兔碗", "Udon"],
    ["兜里", "trong túi"],
    ["全断", "gãy hết"],
    ["八尾", "Bát Vĩ"],
    ["八级", "Level 8"],
    ["八酝", "Yashiori"],
    ["八酿", "Yashiori"],
    ["公子", "Công Tử"],
    ["公鸡", "The Rooster"],
    ["兰利", "Langley"],
    ["兰博", "Rambeau"],
    ["兹踞", "Ziju"],
    ["兹蹻", "Ziqiao"],
    ["冥想", "Calm Mind"],
    ["冥月", "minh nguyệt"],
    ["冰山", "Iceberg"],
    ["冰遁", "băng độn"],
    ["净化", "Thanh Tẩy"],
    ["净眼", "Jougan"],
    ["净蚀", "Búa Gỗ"],
    ["凑齐", "góp đủ"],
    ["凝光", "Nigguang"],
    ["凯亚", "Kaeya"],
    ["凯南", "Kennen"],
    ["凯多", "Kaidou"],
    ["凯尔", "Kayle"],
    ["凯恩", "Caine"],
    ["凯文", "Kevin"],
    ["凯皇", "King Gai"],
    ["凯隐", "Kayn"],
    ["出云", "Izumo"],
    ["刀锋", "Blade"],
    ["分家", "phân gia"],
    ["刚子", "Hagane"],
    ["初代", "Đệ Nhất"],
    ["刻尔", "Keres"],
    ["刻晴", "Keqing"],
    ["前辈", "tiền bối"],
    ["剑姬", "Fiora"],
    ["力库", "Riku"],
    ["加州", "California"],
    ["加菲", "Garfield"],
    ["加藤", "Katō"],
    ["加马", "Gama"],
    ["努努", "Nunu"],
    ["劳斯", "Lawson"],
    ["劳非", "Laufey"],
    ["勇度", "Yondu"],
    ["勘定", "Kanjou"],
    ["北斗", "Beidou"],
    ["十尾", "Thập vĩ"],
    ["十臧", "Juzo"],
    ["十藏", "Juzo"],
    ["千叶", "Chiba"],
    ["千岩", "Thiên Nham"],
    ["千手", "Senju"],
    ["千珏", "Kindred"],
    ["千织", "Chiori"],
    ["千鸟", "Chidori"],
    ["半藏", "Hanzo"],
    ["华代", "Kayo"],
    ["卐解", "Bankai"],
    ["南贺", "Naka"],
    ["博土", "Doctor"],
    ["卡多", "Gatou"],
    ["卡尔", "Kal"],
    ["卡戎", "Charon"],
    ["卡拉", "Karla"],
    ["卡牌", "Twisted Fate"],
    ["卡特", "Katarina"],
    ["卡維", "Kaveh"],
    ["卡维", "Kaveh"],
    ["卡西", "Kakashi"],
    ["卯月", "Uzuki"],
    ["压根", "căn bản*(đè Root)"],
    ["原神", "Genshin"],
    ["原野", "Nohara"],
    ["又旅", "Matatabi"],
    ["取根", "Torune"],
    ["古一", "Ancient One"],
    ["古介", "Kosuke"],
    ["古山", "Furuyama"],
    ["古川", "Furukawa"],
    ["古巴", "Cuba"],
    ["可汗", "Khan"],
    ["可莉", "Klee"],
    ["史恩", "Sean"],
    ["史雷", "Slade"],
    ["叶仓", "Pakura"],
    ["吉乃", "Yoshino"],
    ["后劲", "hậu kình"],
    ["后宫", "hậu cung"],
    ["吞叔", "Galan thúc"],
    ["启太", "Keita"],
    ["周旋", "lượn vòng"],
    ["和马", "Kazuma"],
    ["咪咪", "Mimi"],
    ["哀尔", "Il"],
    ["哈代", "Hardy"],
    ["哈皮", "Happy"],
    ["哎嘿", "Eh he"],
    ["哥谭", "Gotham"],
    ["哲也", "Tetsuya"],
    ["哲夫", "Zeff"],
    ["唐娜", "Donna"],
    ["啊咧", "are"],
    ["啊啦", "ara"],
    ["啊嘞", "ara"],
    ["啊龙", "Arlong"],
    ["嘉丽", "Carrie"],
    ["嘉明", "Gaming"],
    ["嘉颖", "Gia Dĩnh"],
    ["四代", "Đệ Tứ"],
    ["四档", "Gear 4"],
    ["团藏", "Danzō"],
    ["国崩", "Kunikuzushi"],
    ["图奇", "Twitch"],
    ["图灵", "Turing"],
    ["土影", "Tsuchikage"],
    ["土忍", "thổ nhẫn"],
    ["地母", "Địa Mẫu"],
    ["地点", "địa điểm"],
    ["地球", "Địa cầu"],
    ["坂本", "Sakamoto"],
    ["基兰", "Zilean"],
    ["基因", "gen"],
    ["堇瓜", "dưa tím"],
    ["塑茂", "Sakumo"],
    ["塔姆", "TahmKench"],
    ["墨瑟", "Mercer"],
    ["夏姨", "Shakuyaku"],
    ["夏树", "Natsuki"],
    ["夏莉", "Shirley"],
    ["夕颜", "Yūgao"],
    ["多弗", "Dofla"],
    ["多莉", "Dori"],
    ["夜兰", "Yelan"],
    ["夜月", "Yotsuki"],
    ["夜翼", "Nightwing"],
    ["夜魔", "Daredevil"],
    ["大人", "đại nhân"],
    ["大佬", "đại lão"],
    ["大卫", "David"],
    ["大吾", "Daigo"],
    ["大和", "Yamato"],
    ["大嘴", "Kog’Maw"],
    ["大妈", "Big Mom"],
    ["大熊", "Volibear"],
    ["大祐", "Taisuke"],
    ["大福", "Daifuku"],
    ["大群", "Legion"],
    ["大蛇", "Orochi"],
    ["大超", "Superman"],
    ["天使", "Kayle"],
    ["天启", "Apocalypse"],
    ["天天", "Tenten"],
    ["天才", "thiên tài"],
    ["天父", "thiên phụ"],
    ["天狗", "Tengu"],
    ["天理", "Thiên Lý"],
    ["天目", "Amenoma"],
    ["天神", "Celestial"],
    ["天竺", "Ấn Độ"],
    ["天藏", "Tenzō"],
    ["天马", "Pegasus"],
    ["失控", "mất khống chế"],
    ["奈奈", "Nana"],
    ["奈姬", "Nike"],
    ["奈良", "Nara"],
    ["奎因", "Quinn"],
    ["奎恩", "Queen"],
    ["奎斯", "Quested"],
    ["奎西", "Quincy"],
    ["奔驰", "Benz"],
    ["奥兹", "Oars"],
    ["奥妹", "Olsen"],
    ["奥托", "Otto"],
    ["奥措", "Otso"],
    ["奥氏", "Osborn"],
    ["奥藏", "Âu Tàng"],
    ["奧藏", "Âu Tàng"],
    ["女人", "nữ nhân"],
    ["女士", "Signora (nữ sĩ)"],
    ["女警", "Caitlyn"],
    ["奸奇", "Tzeentch"],
    ["如尼", "Rune"],
    ["妇联", "Avengers"],
    ["妙木", "Myoboku"],
    ["妮尔", "Niel"],
    ["妮莎", "Nyssa"],
    ["妮露", "Nilou"],
    ["姐夫", "tỷ phu"],
    ["威利", "Vili"],
    ["娇德", "Jorde"],
    ["娑娜", "Sona"],
    ["娑罗", "Sara"],
    ["娜布", "Nabu"],
    ["娜美", "Nami"],
    ["子铁", "Kotetsu"],
    ["孔苏", "Khonsu"],
    ["孝行", "Takayuki"],
    ["孟邦", "Bang Mon"],
    ["宁录", "Nimrōd"],
    ["守鹤", "Shukaku"],
    ["安伯", "Amber"],
    ["安博", "Amber"],
    ["安妮", "Annie"],
    ["安普", "Anpu"],
    ["安珀", "Amber"],
    ["宗介", "Sousuke"],
    ["宙斯", "Zeus"],
    ["宝马", "BMW"],
    ["实验", "thí nghiệm"],
    ["宵宫", "Yoimiya"],
    ["家族", "gia tộc"],
    ["宾兹", "Binz"],
    ["富丘", "Fugaku"],
    ["富岳", "Fugaku"],
    ["寒意", "hàn ý"],
    ["寝子", "Neko"],
    ["将军", "tướng quân"],
    ["小丑", "Shaco"],
    ["小八", "Hacchi"],
    ["小春", "Koharu"],
    ["小智", "Ash"],
    ["小李", "Rock Lee"],
    ["小樱", "Sakura"],
    ["小法", "Veigar"],
    ["小玉", "Sayu"],
    ["小紫", "Hiyori"],
    ["小葵", "Himawari"],
    ["小鹤", "Tiểu Tsuru"],
    ["尘遁", "Trần độn"],
    ["尤拉", "Eula"],
    ["尤菈", "Eula"],
    ["尼克", "Nick"],
    ["尼可", "Nicole"],
    ["尼桑", "Nii-san"],
    ["尾田", "Oda"],
    ["屏障", "Lá Chắn"],
    ["山中", "Yamanaka"],
    ["山姆", "Sam"],
    ["岚切", "Phong Kiếm"],
    ["岚脚", "Rankyaku"],
    ["岛国", "Nhật Bản"],
    ["岩忍", "ninja Làng Đá"],
    ["岩藏", "Iwakura"],
    ["岩隐", "Nham ẩn"],
    ["岩雀", "Taliyah"],
    ["岸本", "Kishimoto"],
    ["左助", "Sasuke"],
    ["巨魔", "Trundle"],
    ["巳月", "Mitsuki"],
    ["巴尔", "Bael"],
    ["巴德", "Bard"],
    ["巴特", "Bart"],
    ["巴金", "Bakkin"],
    ["巴顿", "Barton"],
    ["市长", "Thị trưởng"],
    ["布朗", "Brown"],
    ["布甲", "Giáp Lụa"],
    ["希尔", "Hill"],
    ["希流", "Shiliew"],
    ["希芙", "Sif"],
    ["希阿", "Shiar"],
    ["帕纳", "Panah"],
    ["带土", "Obito"],
    ["席勒", "Schiller"],
    ["常世", "Tokoyo"],
    ["平藏", "Heizou"],
    ["并足", "Namiashi"],
    ["幸太", "Kota"],
    ["幻月", "Gengetsu"],
    ["幻视", "Vision"],
    ["幽狐", "Sandai Kitetsu"],
    ["库朗", "Clown"],
    ["库郎", "Clown"],
    ["应达", "Ứng Đạt"],
    ["开门", "khai môn"],
    ["引燃", "Thiêu Đốt"],
    ["弗瑞", "Fury"],
    ["弥勒", "Miroku"],
    ["弥彦", "Yahiko"],
    ["归终", "Guizhong"],
    ["影级", "Kage cấp"],
    ["影视", "truyền hình điện ảnh"],
    ["得州", "Texas"],
    ["御舆", "Mikoshi"],
    ["德州", "Texas"],
    ["心海", "Kokomi"],
    ["忍兽", "nhẫn thú"],
    ["忍族", "nhẫn tộc"],
    ["忍术", "nhẫn thuật"],
    ["忍校", "nhẫn giáo"],
    ["忍者", "Ninja"],
    ["忒亚", "Theia"],
    ["志微", "Shibi"],
    ["志间", "Shima"],
    ["快银", "Quicksilver"],
    ["总部", "tổng bộ"],
    ["息灾", "Hủy Diệt"],
    ["恶龍", "Arlong"],
    ["悠米", "Yuumi"],
    ["悦子", "Eiko"],
    ["惑饲", "Wakukau"],
    ["惩戒", "Trừng Phạt"],
    ["想象", "tưởng tượng"],
    ["愚人", "Fatui"],
    ["感电", "điện cảm"],
    ["愣在", "sững sờ ở"],
    ["慈弦", "Jigen"],
    ["慈玄", "Jigen"],
    ["慎介", "Shinsuke"],
    ["慧心", "Tuệ Tâm"],
    ["戈登", "Gordon"],
    ["战国", "Sengoku"],
    ["战衣", "Suit"],
    ["战锤", "Warhammer"],
    ["戴因", "Dain"],
    ["戴森", "Dyson"],
    ["扉间", "Tobirama"],
    ["手打", "Teuchi"],
    ["才能", "tài năng"],
    ["扎斯", "Zsasz"],
    ["托尼", "Tony"],
    ["托斯", "Dosu"],
    ["托比", "Toby"],
    ["托法", "Torfa"],
    ["扩张", "khuếch trương"],
    ["扭断", "vặn gãy"],
    ["披萨", "Pizza"],
    ["拉奥", "Rao"],
    ["拉普", "Rapu"],
    ["拉琪", "Laki"],
    ["拒绝", "cự tuyệt"],
    ["拳头", "nắm đấm"],
    ["拿铁", "Latte"],
    ["指枪", "Shigan"],
    ["振金", "Vibranium"],
    ["捏断", "bóp gãy"],
    ["掘坟", "Yorick"],
    ["提柯", "Tikor"],
    ["提米", "Timmy"],
    ["提莫", "Teemo"],
    ["摩拉", "Mora"],
    ["撞断", "đụng gãy"],
    ["改变", "thay đổi"],
    ["敏锐", "nhạy cảm"],
    ["救赎", "Dây Chuyền Chuộc Tội"],
    ["教子", "Godson"],
    ["教父", "Godfather"],
    ["文太", "Bunta"],
    ["文森", "Vince"],
    ["文武", "Văn Vũ"],
    ["文牙", "Monga"],
    ["斋宫", "Saiguu"],
    ["斧头", "Olaf"],
    ["断裂", "đứt gãy"],
    ["旗木", "Hatake"],
    ["无明", "Mumei"],
    ["日和", "Hiyori"],
    ["日奈", "Hina"],
    ["日差", "Hizashi"],
    ["日斩", "Hiruzen"],
    ["日语", "tiếng Nhật"],
    ["日足", "Hiashi"],
    ["旧神", "Cựu thần"],
    ["时光", "Zilean"],
    ["时空", "thời không"],
    ["旺达", "Wanda"],
    ["明子", "Akiko"],
    ["星云", "Nebula"],
    ["星城", "Star City"],
    ["星爵", "Star Lord"],
    ["晨星", "MorningStar"],
    ["晨曦", "Dawn"],
    ["智人", "Homo sapiens"],
    ["智商", "IQ"],
    ["暹罗", "Thái Lan"],
    ["曼迪", "Mandy"],
    ["月光", "Gekko"],
    ["月关", "Hayate"],
    ["月步", "Geppo"],
    ["月海", "Nguyệt Hải"],
    ["月蓮", "Sen Nilotpala"],
    ["木偶", "Marionette (con rối)"],
    ["木叶", "Konoha"],
    ["木木", "Amumu"],
    ["木漏", "Komore"],
    ["木锤", "Búa Gỗ"],
    ["李青", "LeeSin"],
    ["杰斯", "Jayce"],
    ["松川", "Matsukawa"],
    ["板间", "Itama"],
    ["枇杷", "Biwa"],
    ["林肯", "Lincoln"],
    ["枫丹", "Fontaine"],
    ["枫原", "Kaedehara"],
    ["枫源", "Kaedehara"],
    ["枫达", "Fonta"],
    ["枸橘", "Karatachi"],
    ["柚子", "Yuzu"],
    ["柯萊", "Collei"],
    ["柴达", "Nova"],
    ["树人", "Maokai"],
    ["树根", "rễ cây"],
    ["树王", "Rukkhadevata"],
    ["根据", "căn cứ"],
    ["根源", "căn nguyên"],
    ["根部", "Root"],
    ["格斗", "Fighting"],
    ["格温", "Gwen"],
    ["格雷", "Grey"],
    ["桃式", "Momoshiki"],
    ["桃间", "Tōka"],
    ["梅婶", "Aunt May"],
    ["梅黛", "Mayday"],
    ["梦貘", "Baku"],
    ["梦魇", "Nocturne"],
    ["棍叟", "Stick"],
    ["森乃", "Morino"],
    ["棱堡", "Bastion"],
    ["楼兰", "Rōran"],
    ["樱十", "Ōtō"],
    ["樱哥", "Sakura"],
    ["樹王", "Rukkhadevata"],
    ["欧阿", "Oa"],
    ["欸嘿", "Eh he"],
    ["止水", "Shisui"],
    ["正人", "Masato"],
    ["正联", "Justice League"],
    ["武科", "Vuk"],
    ["死侍", "Deadpool"],
    ["死歌", "Karthus"],
    ["死神", "Tử thần"],
    ["比利", "Billy"],
    ["毛子", "nước Nga"],
    ["毛皮", "Mink"],
    ["氪星", "krypton"],
    ["水原", "Mizuhara"],
    ["水户", "Mito"],
    ["水月", "Suigetsu"],
    ["水木", "Mizuki"],
    ["水遁", "thủy độn"],
    ["汉克", "Hank"],
    ["汉默", "Hammer"],
    ["沙尔", "Sal"],
    ["沙朗", "Sharon"],
    ["沙赞", "Shazam"],
    ["河松", "Kawamatsu"],
    ["法则", "pháp tắc"],
    ["法爷", "Lissandra"],
    ["波兹", "Potts"],
    ["波风", "Namikaze"],
    ["泰坦", "Titan"],
    ["泰隆", "Talon"],
    ["泷忍", "Lang nhẫn"],
    ["洛娜", "Lorna"],
    ["活蝓", "Katsuya"],
    ["派对", "Party"],
    ["浅濑", "Asase"],
    ["浦式", "Urashiki"],
    ["浪人", "ronin"],
    ["浮舍", "Phù Xá"],
    ["海德", "Hyde"],
    ["海文", "Haven"],
    ["海滩", "bãi biển"],
    ["海祇", "Watatsumi"],
    ["海衹", "Watatsumi"],
    ["海野", "Umino"],
    ["涂鸦", "Graffiti"],
    ["涡忍", "Uzumaki ninja"],
    ["涡潮", "Uzumaki"],
    ["润媞", "Ulti"],
    ["深座", "Fukasaku"],
    ["清弥", "Kiyomi"],
    ["清簌", "Seirai"],
    ["清籁", "Seirai"],
    ["渊下", "Enjou"],
    ["渣康", "Constantine"],
    ["温蒂", "Venti"],
    ["温迪", "Venti"],
    ["溶遁", "dung độn"],
    ["满月", "Mangetsu"],
    ["漩涡", "Uzumaki"],
    ["潘乔", "Pancho"],
    ["潘森", "Pantheon"],
    ["火女", "Annie"],
    ["火影", "Hokage"],
    ["火种", "hỏa chủng"],
    ["火箭", "hỏa tiễn*(Rocket)"],
    ["火花", "Hanabi"],
    ["火遁", "hỏa độn"],
    ["灭霸", "Thanos"],
    ["灯戒", "Lantern"],
    ["灯笼", "Thresh"],
    ["灰河", "Fleuve Cendre"],
    ["灵碟", "Psylocke"],
    ["灵风", "Phong Kiếm"],
    ["炸断", "nổ gãy"],
    ["烟绯", "Yanfei"],
    ["烬寂", "Mare Jivari"],
    ["热狗", "Hotdog"],
    ["照美", "Terumi"],
    ["燃素", "Phlogiston"],
    ["爱射", "Ashe"],
    ["爱诺", "Aino"],
    ["版纳", "Banner"],
    ["牛逼", "ngưu bức"],
    ["牛鬼", "Gyūki"],
    ["犀犬", "Saiken"],
    ["狂攻", "Onslaught"],
    ["狄耶", "X"],
    ["狐妖", "hồ yêu"],
    ["狗头", "Nasus"],
    ["狱卒", "quản ngục"],
    ["狼末", "Đường cùng của sói"],
    ["狼母", "Ambessa"],
    ["狼獾", "Wolverine"],
    ["猎鹰", "Falcon"],
    ["猫女", "Catwoman"],
    ["猿飞", "Sarutobi"],
    ["猿魔", "Enma"],
    ["玄间", "Genma"],
    ["王直", "Wang Zhi"],
    ["玛菲", "Murphy"],
    ["玲玲", "Linlin"],
    ["玻瓦", "Bolivar"],
    ["珍玛", "Jemma"],
    ["班德", "Bande"],
    ["球女", "Syndra"],
    ["琉璃", "Lưu Ly"],
    ["琴了", "Jean"],
    ["琴女", "Sona"],
    ["瑜伽", "Yoga"],
    ["瑞丝", "Ryze"],
    ["瑞克", "Rick"],
    ["瑞安", "Ryan"],
    ["瑞德", "Rhett"],
    ["瑞文", "Raven"],
    ["瑶瑶", "Yaoyao"],
    ["璐璐", "Lulu"],
    ["瓦间", "Kawarama"],
    ["甘雨", "Ganyu"],
    ["田岛", "Tajima"],
    ["申鹤", "Shenhe"],
    ["电影", "điện ảnh"],
    ["电索", "Cable"],
    ["男枪", "Graves"],
    ["留云", "Lưu Vân"],
    ["疯帽", "Jervis Tetch"],
    ["病毒", "Virus"],
    ["白术", "Baizhu"],
    ["白痴", "đứa đần"],
    ["白绝", "Zetsu Trắng"],
    ["白舞", "Hakumai"],
    ["白莲", "Byakuren"],
    ["白辰", "Hakushin"],
    ["百晓", "Bách Hiểu"],
    ["百闻", "Bách Văn"],
    ["皇子", "Jarvan IV"],
    ["皎月", "Diana"],
    ["皮卡", "xe bán tải"],
    ["皮城", "Vi"],
    ["皮姆", "Pym"],
    ["盖亚", "Gaia"],
    ["盖伦", "Garen"],
    ["直树", "Naoki"],
    ["真君", "Chân Quân"],
    ["真红", "Shinku"],
    ["瞬移", "Teleport"],
    ["知易", "Zhiyi"],
    ["知比", "Shirikoro"],
    ["短命", "đoản mệnh"],
    ["石川", "Ishikawa"],
    ["矶怃", "Isobe"],
    ["矶抚", "Isobe"],
    ["砂糖", "Sucrose"],
    ["砂隐", "Sa ẩn"],
    ["碧压", "Bia"],
    ["祖利", "Zuri"],
    ["神乐", "Kagura"],
    ["神威", "Kamui"],
    ["神子", "Miko"],
    ["神性", "thần tính"],
    ["神月", "Kamizuki"],
    ["神父", "cha xứ"],
    ["神职", "thần chức"],
    ["神鹤", "Kamizuru"],
    ["福吉", "Foggy"],
    ["福林", "Fring"],
    ["福柏", "Phoebe"],
    ["福瑞", "Fury"],
    ["离岛", "Ritou đảo"],
    ["秀一", "Shuichi"],
    ["秋水", "Shusui"],
    ["秋道", "Akimichi"],
    ["秘客", "Magik"],
    ["秘能", "bí năng"],
    ["稻城", "Inagi"],
    ["穆托", "Muto"],
    ["空岛", "Skypiea"],
    ["空的", "Aether"],
    ["空良", "Sora"],
    ["竹取", "Kaguya"],
    ["笈名", "Oina"],
    ["笹目", "Sasame"],
    ["米奇", "Mickey"],
    ["米德", "Midgard"],
    ["紐约", "New York"],
    ["索芬", "Sofen"],
    ["紫人", "Purple Man"],
    ["綱手", "Tsunade"],
    ["红发", "Tóc Đỏ"],
    ["红房", "Red Room"],
    ["红莲", "Guren"],
    ["红豆", "Anko"],
    ["级别", "cấp bậc"],
    ["纳塔", "Natlan"],
    ["纳尔", "Knull"],
    ["纳布", "Nebo"],
    ["纳米", "Nano"],
    ["纸绘", "Kami-e"],
    ["纽約", "New York"],
    ["纽顿", "Newton"],
    ["绀田", "Konda"],
    ["终端", "thiết bị kết nối"],
    ["绫人", "Ayato"],
    ["绳树", "Nawaki"],
    ["维度", "chiều không gian"],
    ["维恩", "Wayne"],
    ["维戈", "Viggo"],
    ["维迦", "Veigar"],
    ["绿川", "Midori"],
    ["绿箭", "Green Arrow"],
    ["缇娜", "Hina"],
    ["编笠", "Amigasa"],
    ["缝针", "Nuibari"],
    ["罗姗", "Roxanne"],
    ["罗布", "Rob"],
    ["罗德", "Rhodes"],
    ["罗杰", "Roger"],
    ["罗根", "Logan"],
    ["罗沙", "Rasa"],
    ["罗砂", "Rasa"],
    ["罗迪", "Rhodes"],
    ["美刀", "USD"],
    ["美国", "Mỹ quốc"],
    ["美女", "mỹ nữ"],
    ["美波", "Minami"],
    ["美琴", "Mikoto"],
    ["羽衣", "Hagoromo"],
    ["羽高", "Utakata"],
    ["耀光", "Thủy Kiếm"],
    ["老墨", "lão Mep"],
    ["老登", "lão già"],
    ["老紫", "Rōshi"],
    ["老鼠", "Twitch"],
    ["考德", "Code"],
    ["能力", "năng lực"],
    ["能量", "năng lượng"],
    ["自也", "Jiraiya"],
    ["舍人", "Toneri"],
    ["船长", "Gangplank"],
    ["良介", "Ryosuke"],
    ["艾克", "Ekko"],
    ["艾咪", "Amy"],
    ["艾因", "Ain"],
    ["艾尔", "El"],
    ["艾希", "Ashe"],
    ["艾斯", "Ace"],
    ["艾玛", "Emma"],
    ["艾琳", "Ellin"],
    ["艾达", "Ada"],
    ["艾迪", "Eddie"],
    ["芙芙", "Funa"],
    ["芬德", "Vind"],
    ["花火", "Hanabi"],
    ["苏打", "Soda"],
    ["苏睿", "Shuri"],
    ["苏里", "Shuri"],
    ["苦无", "kunai"],
    ["茂凯", "Maokai"],
    ["茂朔", "Sakumo"],
    ["范马", "Hanma"],
    ["茉莉", "Jasmine"],
    ["草人", "Fiddlesticks"],
    ["草神", "Thảo Thần"],
    ["荒泷", "Arataki"],
    ["荣兹", "JOnzz"],
    ["药师", "Yakushi"],
    ["莎伦", "Sharon"],
    ["莫娜", "Mona"],
    ["莫拉", "Moira"],
    ["莫都", "Mordo"],
    ["莱恩", "Reeyn"],
    ["莱蒂", "Letty"],
    ["菲兹", "Fitz"],
    ["菲碧", "Phoebe"],
    ["菲间", "Tobirama"],
    ["萝莉", "Jinx"],
    ["萤美", "Hotomi"],
    ["萨利", "Sāra"],
    ["萨塔", "Zartha"],
    ["萨奇", "Thatch"],
    ["萨总", "Sargeras"],
    ["萨满", "Shaman"],
    ["葛蕾", "Grey"],
    ["蒂凡", "Tivan"],
    ["蒙多", "Dr. Mundo"],
    ["蒙德", "Mondstadt"],
    ["蓝砚", "Lan Yan"],
    ["薄饼", "Bánh kếp"],
    ["薇恩", "Vayne"],
    ["藤兜", "Fujitou"],
    ["藤野", "Fujino"],
    ["虚弱", "Kiệt Sức"],
    ["虫子", "Kha’Zix"],
    ["蚁人", "Ant-man"],
    ["蛇女", "Cassiopeia"],
    ["蛤蟆", "Tahm Kench"],
    ["蛮王", "Tryndamere"],
    ["蜂刺", "Kiếm Chích"],
    ["蜘蛛", "Elise"],
    ["蝎子", "Skarner"],
    ["蝰蛇", "Viper"],
    ["蝶蝶", "Chocho"],
    ["螳螂", "Kha’Zix"],
    ["血清", "huyết thanh"],
    ["血脉", "huyết mạch"],
    ["行秋", "Xingqiu"],
    ["袛园", "Momousagi"],
    ["褔吉", "Fudge"],
    ["西芙", "Sif"],
    ["西蒙", "Seamus"],
    ["角都", "Kakuzu"],
    ["触手", "Vel’Koz"],
    ["詹米", "Jamie"],
    ["该隐", "Cain"],
    ["请仙", "thỉnh tiên"],
    ["诺克", "Garen"],
    ["诺娃", "Nova"],
    ["诺恩", "Noen"],
    ["诺林", "Norrin"],
    ["诺瓦", "Nova"],
    ["谎话", "lời nói dối"],
    ["谢伊", "Shay"],
    ["豹女", "Nidalee"],
    ["賽諾", "Cyno"],
    ["贝利", "Belly"],
    ["贝姬", "Becky"],
    ["贝恩", "Bane"],
    ["贝格", "Berg"],
    ["贝齐", "Betsy"],
    ["费斯", "Frost"],
    ["贾巴", "Jappa"],
    ["赖得", "Rider"],
    ["赛娜", "Senna"],
    ["赛恩", "Sion"],
    ["赤丸", "Akamaru"],
    ["赤穗", "Ako"],
    ["赫曼", "Hermann"],
    ["赵信", "XinZhao"],
    ["超人", "Superman"],
    ["超女", "Supergirl"],
    ["超霸", "Ultraman"],
    ["跋掣", "Beisht"],
    ["路飞", "Luffy"],
    ["身份", "thân phận"],
    ["轻策", "Khinh Sách"],
    ["辛焱", "Xinyan"],
    ["达旦", "Dadan"],
    ["达茜", "Darcy"],
    ["迈克", "Might"],
    ["迈特", "Might"],
    ["进帐", "tiến vào"],
    ["远征", "viễn chinh"],
    ["迭加", "điệp gia"],
    ["道启", "Doukei"],
    ["道胤", "Douin"],
    ["那菈", "Nara"],
    ["邦迪", "Byrnndi"],
    ["酒保", "Bartender"],
    ["酒桶", "Gragas"],
    ["里克", "Rick"],
    ["里昂", "Lyon"],
    ["里角", "Urakaku"],
    ["重云", "Chongyun"],
    ["重明", "Chōmei"],
    ["野原", "Nohara"],
    ["金尼", "Kinney"],
    ["金并", "Kingpin"],
    ["金角", "Kinkaku"],
    ["钟离", "Zhongli"],
    ["钢骨", "Kong"],
    ["铁块", "Tekkai"],
    ["铁幕", "Iron Curtain"],
    ["铁火", "Tekka"],
    ["铁男", "Mordekaiser"],
    ["铃后", "Ringo"],
    ["铜雀", "Đồng Tước"],
    ["银护", "Guardians of the Galaxy"],
    ["银斧", "Silver Axe"],
    ["银角", "Ginkaku"],
    ["锅巴", "Guoba"],
    ["锐雯", "Riven"],
    ["锤石", "Thresh"],
    ["长剑", "Kiếm Dài"],
    ["长正", "Nagamasa"],
    ["长野", "Nagano"],
    ["门炎", "Homura"],
    ["门罗", "Munroe"],
    ["闪烁", "Blink"],
    ["闪现", "Tốc Biến"],
    ["闲云", "Xianyun"],
    ["队长", "Captain"],
    ["阴遁", "Âm độn"],
    ["阿丑", "Ushi"],
    ["阿健", "Genzo"],
    ["阿凯", "Gai"],
    ["阿响", "Hibiki"],
    ["阿如", "Aaru"],
    ["阿拉", "ara"],
    ["阿晃", "Akira"],
    ["阿桂", "Gui"],
    ["阿玉", "Tama"],
    ["阿福", "Alfred"],
    ["阿贝", "Albedo"],
    ["阿釜", "Kama"],
    ["阿飞", "Tobi"],
    ["院长", "viện trưởng"],
    ["陶德", "Todd"],
    ["隆中", "Ryū-chū"],
    ["雅典", "Athens"],
    ["雅威", "Yahweh"],
    ["雏田", "Hinata"],
    ["雨忍", "ninja Làng Mưa"],
    ["雨隐", "Làng Mưa ninja"],
    ["雪绪", "Yukio"],
    ["零尾", "linh vĩ"],
    ["雷同", "Raido"],
    ["雷尼", "Rainey"],
    ["雷泽", "Razor"],
    ["雷牙", "Raiga"],
    ["雷玖", "Reiju"],
    ["雷神", "Thần Sấm"],
    ["雷蒙", "Raymond"],
    ["雷遁", "lôi độn"],
    ["雾切", "Ánh Sáng Đem Sương Mù"],
    ["雾忍", "Vụ nhẫn"],
    ["雾隐", "Vụ ẩn"],
    ["霄宫", "Yoimiya"],
    ["霍尔", "Hall"],
    ["霍根", "Hogan"],
    ["霍迪", "Hodi"],
    ["霜月", "Shimotsuki"],
    ["露丝", "Ruth"],
    ["露比", "Ruby"],
    ["露玖", "Rouge"],
    ["露露", "Lulu"],
    ["青年", "thanh niên"],
    ["青椒", "Chinjao"],
    ["青稚", "Aokiji"],
    ["青衣", "áo xanh"],
    ["静子", "Shizuko"],
    ["静音", "Shizune"],
    ["靜音", "Shizune"],
    ["面麻", "Menma"],
    ["鞍马", "Kurama"],
    ["韦伦", "Waylon"],
    ["韦德", "Wade"],
    ["顶篷", "Canopy"],
    ["须弥", "Sumeru"],
    ["风女", "Janna"],
    ["风祭", "Kazamatsuri"],
    ["风遁", "phong độn"],
    ["风魔", "Fūma"],
    ["飞机", "Corki"],
    ["飞段", "Hidan"],
    ["飞沫", "Shibuki"],
    ["飞船", "phi thuyền"],
    ["首富", "Richest"],
    ["香波", "Sabaody"],
    ["香港", "Hồng Kông"],
    ["香燐", "Karin"],
    ["香菱", "Karin"],
    ["马修", "Matthew"],
    ["马克", "Mark"],
    ["马可", "Marko"],
    ["马宏", "Mahone"],
    ["马龙", "Malone"],
    ["高丽", "Hàn quốc"],
    ["高达", "Gundam"],
    ["鬼交", "Kisame"],
    ["鬼灯", "Hoozuki"],
    ["鬼胶", "Kisame"],
    ["鬼鲛", "Kisame"],
    ["魅惑", "mị hoặc"],
    ["魔力", "ma lực"],
    ["魔神", "Majin"],
    ["魔腾", "Nocturne"],
    ["鲆鲽", "Hiramekarei"],
    ["鲛肌", "Samehada"],
    ["鲨星", "Fukaboshi"],
    ["鳄鱼", "Renekton"],
    ["鳴人", "Naruto"],
    ["鸟人", "Quinn"],
    ["鸠助", "Kyūsuke"],
    ["鸣人", "Naruto"],
    ["鸣子", "Naruko"],
    ["鸣神", "Narukami"],
    ["鹤观", "Tsurumi đảo"],
    ["鹰司", "Takatsukasa"],
    ["鹰眼", "Hawk Eye"],
    ["鹿丸", "Shikamaru"],
    ["鹿代", "Shikadai"],
    ["鹿戴", "Shikadai"],
    ["黄印", "Kijirushi"],
    ["黄土", "Kitsuchi"],
    ["黄猿", "Kizaru"],
    ["黑化", "hắc hóa"],
    ["黑帮", "Gangster"],
    ["黑心", "Blackheart"],
    ["黑洞", "Black Hole"],
    ["黑炭", "Kurozumi"],
    ["黑田", "Kuroda"],
    ["黑皇", "Black King"],
    ["黑空", "Elektra"],
    ["黑腕", "Black Arm"],
    ["黑锄", "Kurosuki"],
    ["黛因", "Dyne"],
    ["黛娜", "Dinah"],
    ["黛比", "Debbie"],
    ["齐史", "Masashi"],
    ["龙女", "Shyvana"],
    ["龙神", "Dragon thần"],
    ["龙马", "Ryuma"],
    ["一斗了", "Itto"],
    ["七人众", "Shichinin Shū"],
    ["七武海", "Shichibukai"],
    ["万力王", "Graviton"],
    ["万花筒", "Mangekyou"],
    ["万达格", "Wundagore"],
    ["三代目", "Đệ Tam"],
    ["三明治", "Sandwich"],
    ["上帝啊", "Jesus"],
    ["上水流", "Kamizuru"],
    ["上百万", "hơn triệu"],
    ["不卜庐", "Bubu"],
    ["不老泉", "bất lão tuyền"],
    ["丛云切", "Murakumogiri"],
    ["东海岸", "East Coast"],
    ["两天秤", "Lưỡng Thiên Xứng"],
    ["丰颂府", "Tỉnh Mae Hong Son"],
    ["丸太郎", "Taroumaru"],
    ["丹弗丝", "Danvers"],
    ["丽亚娜", "Illyana"],
    ["丽桑卓", "Lissandra"],
    ["久利须", "Kurisu"],
    ["久辛奈", "Kushina"],
    ["乌索布", "Usopp"],
    ["乌迪尔", "Udyr"],
    ["乌阿图", "Uatu"],
    ["乐芙兰", "Leblanc"],
    ["乔丹尼", "Jordani"],
    ["乔艾尔", "Jor El"],
    ["九喇嘛", "Kurama"],
    ["九岐忍", "Kuki Shinobu"],
    ["二代目", "Đệ Nhị"],
    ["二柱子", "Sasuke"],
    ["云影村", "Làng Mây"],
    ["云忍村", "Làng Mây"],
    ["云隐忍", "Làng Mây ninja"],
    ["云隐村", "Làng Mây"],
    ["五代目", "Đệ Ngũ"],
    ["五百藏", "Ioroi"],
    ["五面怪", "Quintessons"],
    ["亚克莱", "Alkali"],
    ["亚兰戈", "Yalan · Gur"],
    ["亚图姆", "Atum"],
    ["亚天父", "Á thiên phụ"],
    ["交换下", "trao đổi"],
    ["人柱力", "Jinchūriki"],
    ["人造人", "người nhân tạo"],
    ["从云切", "Murakumogiri"],
    ["仿生鸟", "Mockingbird"],
    ["伊万卡", "Ivanka"],
    ["伊安珊", "Iansan"],
    ["伊文斯", "Evans"],
    ["伊特利", "Etruria"],
    ["伊瓦诺", "Evanora"],
    ["伊莉丝", "Elise"],
    ["伊莫顿", "Imhotep"],
    ["伊那利", "Inari"],
    ["传次郎", "Denjiro"],
    ["住吉会", "Sumiyoshi-kai"],
    ["佛卡洛", "Focalor"],
    ["佩吉万", "Page One"],
    ["俄洛伊", "Illaoi"],
    ["保尔森", "Borson"],
    ["保护伞", "Umbrella"],
    ["俱乐部", "Club"],
    ["兄弟会", "Brotherhood"],
    ["克劳德", "Claude"],
    ["克劳萨", "Krauser"],
    ["克劳馥", "Croft"],
    ["克尔拉", "Koala"],
    ["克拉尔", "Koala"],
    ["克拉科", "Krakoa"],
    ["克来因", "Crane"],
    ["克林特", "Clint"],
    ["克苏鲁", "Cthulhu"],
    ["克莱恩", "Klein"],
    ["克里尔", "Creel"],
    ["克里斯", "Chris"],
    ["克里特", "Crete"],
    ["克鲁人", "Skrull người"],
    ["八咫鸟", "Yatagarasu"],
    ["兰伊舍", "Araesha"],
    ["兰伽卢", "Arakara"],
    ["兰拉迦", "Araja"],
    ["兰罗摩", "Arama"],
    ["兰茶荼", "Arachatora"],
    ["兰那罗", "Aranara"],
    ["共济会", "Hội tam điểm"],
    ["共生体", "Symbiote"],
    ["内瑟斯", "Nasus"],
    ["写作业", "làm bài tập"],
    ["冬妮娅", "Tonia"],
    ["冲云霄", "Predaking"],
    ["净善宫", "Surasthana cung điện"],
    ["凌人的", "Ayato"],
    ["凝光大", "Ningguang đại"],
    ["凝光是", "Ningguang là"],
    ["凝光的", "Ningguang"],
    ["几十亿", "mấy tỷ"],
    ["几百万", "mấy triệu"],
    ["凡冈萨", "Venganza"],
    ["凯尹拉", "Caiera"],
    ["凯尼格", "Koenig"],
    ["凯撒宫", "Caesars Palace"],
    ["凯特琳", "Caitlyn"],
    ["凯瑞亚", "Khaenriah"],
    ["凯瑟琳", "Catherine"],
    ["刚子铁", "Hagane Kotetsu"],
    ["初代目", "Đệ Nhất"],
    ["别天神", "Koto Amatsukami"],
    ["刻师傅", "Keqing sư phó"],
    ["刻莱诺", "Celaeno"],
    ["功能卡", "công năng tạp"],
    ["加拿大", "Canada"],
    ["加特勒", "Garrett"],
    ["加米尔", "Gamiel"],
    ["加藤断", "Kato Dan"],
    ["加藤段", "Katō Dan"],
    ["加里奥", "Galio"],
    ["加麻大", "Canada"],
    ["劫波莲", "Sen Kalpalata"],
    ["劫波蓮", "Sen Kalpalata"],
    ["勇罗格", "Yon Rogg"],
    ["化城郭", "Gandharva làng"],
    ["北极星", "Polaris"],
    ["匝瑳市", "Sōsa thành phố"],
    ["十环帮", "Ten Rings"],
    ["千里眼", "Clairvoyant"],
    ["华盛顿", "Washington"],
    ["卑留呼", "Hiruko"],
    ["博人传", "Boruto"],
    ["博尔森", "Borson"],
    ["博尔颂", "Bolborn"],
    ["博莱塔", "Beretta"],
    ["卡列班", "Caliban"],
    ["卡卡西", "Kakashi"],
    ["卡奇纳", "Kachina"],
    ["卡尔马", "Karma"],
    ["卡忒琳", "Catarina"],
    ["卡斯柏", "Casper"],
    ["卡珊卓", "Cassandra"],
    ["卡罗尔", "Carol"],
    ["卡莫拉", "Gamorra"],
    ["卡蜜尔", "Camille"],
    ["卡里法", "Kalifa"],
    ["卡马拉", "Kamala"],
    ["卡魔拉", "Gamora"],
    ["卡麦隆", "Cameron"],
    ["卢内拉", "Lunella"],
    ["卢浮宫", "Viện bảo tàng Louvre"],
    ["卢锡安", "Lucian"],
    ["印杜洋", "Ấn Độ dương"],
    ["厄加特", "Urgot"],
    ["原野琳", "Nohara Rin"],
    ["反黑帮", "Anti-Gangster"],
    ["变种人", "Mutant"],
    ["古德温", "Godwin"],
    ["叫日向", "gọi Hyuga"],
    ["史代西", "Stacy"],
    ["史来姆", "slime"],
    ["史蒂芬", "Stephen"],
    ["叶莲娜", "Yelena"],
    ["司法岛", "Enies Lobby"],
    ["吉扎斯", "Jesus"],
    ["吉诺沙", "Genosha"],
    ["向日葵", "Himawari"],
    ["向火影", "hướng Hokage"],
    ["吸收人", "Absorbing Man"],
    ["吸血鬼", "Vampire"],
    ["呀咩咯", "ya me ro"],
    ["和小樱", "cùng Sakura"],
    ["和璞鸢", "Hòa Phác Diên"],
    ["咏春拳", "vịnh xuân quyền"],
    ["咕啦啦", "Gu ra ra"],
    ["哈密尔", "Hamir"],
    ["哈拉星", "Hala tinh"],
    ["哈曼顿", "Manhattan"],
    ["哥吉拉", "Godzilla"],
    ["哲平的", "Teppie"],
    ["善见地", "Ashavan lãnh địa"],
    ["嘉布拉", "Gabriela"],
    ["嘟嘟莲", "Calla Lily"],
    ["嘿嗨爪", "Hail Hydra"],
    ["四代目", "Đệ Tứ"],
    ["因特尔", "Intel"],
    ["因论派", "Vahumana"],
    ["因陀罗", "Indra"],
    ["土之国", "Thổ Quốc"],
    ["圣洁会", "Thánh Khiết hội"],
    ["圣胡安", "Sanjuan"],
    ["在忍校", "tại Ninja trường học"],
    ["在暗部", "tại ám bộ"],
    ["地中海", "Địa Trung Hải"],
    ["地怨虞", "Địa Oán Ngu"],
    ["地狱谷", "Jigokudani"],
    ["坎蒂丝", "Candace"],
    ["坎蒂絲", "Candace"],
    ["坦利亚", "Taneleer"],
    ["埃和星", "Morag tinh"],
    ["埃洛伊", "Aloy"],
    ["埃里克", "Erik"],
    ["基尼奇", "Kinich"],
    ["基诺思", "Genus"],
    ["基诺沙", "Kenosha"],
    ["基金会", "hội ngân sách"],
    ["塔利雅", "Dahlia"],
    ["塔希堤", "Tahiti"],
    ["塔希提", "T.A.H.I.T.I"],
    ["塔莉垭", "Taliyah"],
    ["塞勒尔", "Serrure"],
    ["塞拉斯", "Sylas"],
    ["塞琉斯", "Cyrus"],
    ["塞维格", "Selvig"],
    ["墨菲特", "Malphite"],
    ["壳组织", "Kara tổ chức"],
    ["夏延山", "Cheyenne núi"],
    ["夏沃蕾", "Chevreuse"],
    ["夏洛蒂", "Charlotte"],
    ["夕阳红", "Yuuhi Kurenai"],
    ["多托雷", "Dottore"],
    ["多玛姆", "Dormammu"],
    ["多由野", "Tayuya"],
    ["多莱姆", "Dominic"],
    ["多角者", "The Many Angled Ones"],
    ["夜叉丸", "Yashamaru"],
    ["夜总会", "Nightclub"],
    ["夜莺队", "Nightingales"],
    ["夜魔侠", "Daredevil"],
    ["大主教", "đại chủ giáo"],
    ["大伟丘", "Wei Hilichurl"],
    ["大天使", "Đại thiên sứ"],
    ["大富豪", "nhà giàu"],
    ["大忍族", "đại nhẫn tộc"],
    ["大快刀", "Ō Wazamono"],
    ["大柱子", "Đại Trụ Tử"],
    ["大溪地", "Tahiti"],
    ["大祭司", "Đại tế ti"],
    ["大蛇丸", "Orochimaru"],
    ["大蛤蟆", "Gamamaru"],
    ["大郎丸", "Taroumaru"],
    ["大野木", "Ōnoki"],
    ["大魔女", "đại ma nữ"],
    ["天使长", "thiên sứ trưởng"],
    ["天剑局", "S.W.O.R.D cục"],
    ["天守阁", "Thiên Thủ Các"],
    ["天目影", "Amenoma"],
    ["天神组", "Celestial"],
    ["天臂池", "Yazadaha hồ"],
    ["太平洋", "Thái Bình dương"],
    ["太郎丸", "Taroumaru"],
    ["夸格斯", "Qrazgoth"],
    ["奇塔瑞", "Chitauri"],
    ["奇拉比", "Killer Bee"],
    ["奈芙尔", "Nefer"],
    ["奔狼领", "Lang Lĩnh"],
    ["奥丁森", "Odinson"],
    ["奥巴达", "Obadiah"],
    ["奥拉夫", "Olaf"],
    ["奥摩伊", "Omoi"],
    ["奥斯汀", "Austin"],
    ["奥术师", "áo thuật sư"],
    ["奥淑图", "Oshutu"],
    ["奥莉薇", "Olivia"],
    ["奥藏山", "Âu Tàng Sơn"],
    ["奥赛尔", "Osial"],
    ["妙木山", "Diệu Mộc Sơn"],
    ["妙論派", "Kshahrewar"],
    ["威尔逊", "Wilson"],
    ["威布尔", "Weevil"],
    ["娜维娅", "Navia"],
    ["孙悟空", "MonkeyKing"],
    ["宇智波", "Uchiha"],
    ["安德洛", "Androm"],
    ["安琪尔", "Angel"],
    ["安禄山", "Mukade"],
    ["安苏娜", "Ancksunamun"],
    ["宝莱坞", "Bollywood"],
    ["宾杰克", "Byojack"],
    ["小七七", "tiểu Qiqi"],
    ["小南南", "tiểu Konan"],
    ["小法师", "Veigar"],
    ["小甘雨", "tiểu Ganyu"],
    ["小萝莉", "tiểu loli"],
    ["小辣椒", "Pepper"],
    ["小鱼人", "Fizz"],
    ["尤里卡", "JAEGER"],
    ["尸澄真", "Shizuma"],
    ["尹戈尔", "Igo"],
    ["尼克斯", "Nyx"],
    ["尼克森", "Nickerson"],
    ["尼格马", "Nygma"],
    ["尾兽玉", "Bijūdama"],
    ["尾立鼠", "Otachi"],
    ["山多拉", "Shandorian"],
    ["山椒鱼", "Salamander"],
    ["岩上茶", "Trà Trên Đá"],
    ["岩之国", "Thổ Quốc"],
    ["岩影村", "Làng Đá"],
    ["岩忍村", "Làng Đá"],
    ["岩藏流", "Iwakura phái"],
    ["峡谷外", "ngoài hẻm núi"],
    ["崔斯克", "Trask"],
    ["巡林员", "kiểm lâm"],
    ["工程师", "công trình sư"],
    ["巨魔王", "Trundle"],
    ["巫心魔", "Blackheart"],
    ["巴克希", "Bakshi"],
    ["巴博萨", "Barbossa"],
    ["巴斯克", "Basuko"],
    ["巴杰斯", "Burgess"],
    ["巴沙斯", "Burgess"],
    ["布伦妮", "Prune"],
    ["布兰德", "Brand"],
    ["布利克", "Bleecker"],
    ["布来德", "Brad"],
    ["布耶爾", "Buer"],
    ["布里克", "Bleecker"],
    ["布里夫", "Brief"],
    ["布里茨", "Blitzcrank"],
    ["希尔维", "Sylvie"],
    ["希瓦娜", "Shyvana"],
    ["希维尔", "Sivir"],
    ["希诺宁", "Xilonen"],
    ["帕提斯", "Pallas"],
    ["帕琉斯", "Peleus"],
    ["带兜帽", "mang mũ trùm"],
    ["常世国", "Tokoyokoku"],
    ["平克曼", "Pinkman"],
    ["幻翎洛", "Rakan"],
    ["庇特圣", "St. Peter"],
    ["库拉拉", "Gu ra ra"],
    ["库蕾哈", "Kureha"],
    ["康纳斯", "Connors"],
    ["异人族", "Inhumans"],
    ["弗莉嘉", "Frigga"],
    ["弗莱格", "Flag"],
    ["弗莱肯", "Flerken"],
    ["弗里斯", "Fries"],
    ["当火影", "làm Hokage"],
    ["彼得森", "Peterson"],
    ["御手洗", "Mitarashi"],
    ["德拉姆", "Drumm"],
    ["德莱文", "Draven"],
    ["心形草", "tâm hình thảo"],
    ["心转身", "tâm chuyển thân"],
    ["快刀陈", "Trần Khoái Đao"],
    ["恩乔布", "NJobu"],
    ["恰斯卡", "Chasca"],
    ["恶政王", "Abaro Pisaro"],
    ["情人节", "Valentine"],
    ["惠比寿", "Ebisu"],
    ["惩罚者", "Punisher"],
    ["意大利", "Italy"],
    ["慧星帮", "Comet Gang"],
    ["我开动", "Itadakimasu~"],
    ["我爱罗", "Gaara"],
    ["我腿断", "ta chân gãy"],
    ["戴克斯", "Dax"],
    ["扇子妈", "Karma"],
    ["手和会", "The Hand"],
    ["手里剑", "shuriken"],
    ["托尔顿", "Thor"],
    ["托普曼", "Topman"],
    ["托特兰", "Totto Land"],
    ["托马雷", "Tomar · Re"],
    ["把火影", "đem Hokage"],
    ["护世森", "Lokapala đại sâm lâm"],
    ["护驾！", "Hộ Giá!"],
    ["拉什曼", "Rushman"],
    ["拉克丝", "Lux"],
    ["拉娜蓝", "Lana Lang"],
    ["拉沃娜", "Ravonna"],
    ["拉莫斯", "Rammus"],
    ["挖掘机", "Rek’Sai"],
    ["振金矿", "vibranium khoáng"],
    ["掌心炮", "Palm Cannon"],
    ["提华纳", "Tijuana"],
    ["提米的", "Timmy"],
    ["提纳里", "Tighnari"],
    ["提里昂", "Tyrion"],
    ["摩尔斯", "Morse"],
    ["摩拉了", "Mora"],
    ["撒坦尼", "Satannish"],
    ["擎天柱", "Optimus Prime"],
    ["收垃圾", "thu rác rưởi"],
    ["收藏家", "Collector"],
    ["收集者", "Collector"],
    ["文森特", "Vincent"],
    ["斯伯洛", "Sparrow"],
    ["斯克鲁", "Skrull"],
    ["斯卡纳", "Skarner"],
    ["斯嘉莉", "Scarlett"],
    ["斯坦尼", "Stane"],
    ["斯塔克", "Stark"],
    ["斯巴达", "Sparta"],
    ["斯拉普", "Slap"],
    ["斯杰夫", "Steve"],
    ["斯特拉", "Strucker"],
    ["斯特鲁", "Skrull"],
    ["斯维因", "Swain"],
    ["斯莱德", "Slade"],
    ["新之助", "Shinnosuke"],
    ["新月轩", "Tân Nguyệt Hiên"],
    ["施拉德", "Schrader"],
    ["无畏舰", "Dreadnought hạm"],
    ["日行者", "Daywalker"],
    ["昆塔莎", "Quintessa"],
    ["昆布丸", "Konbumaru"],
    ["明冠峡", "Minh Quán hẻm núi"],
    ["明论派", "Rtawahist"],
    ["普利策", "Pulitzer"],
    ["普朗克", "Gangplank"],
    ["晴之介", "Harunosuke"],
    ["暴风女", "Storm"],
    ["曼提斯", "Mantis"],
    ["曼蛤顿", "Manhattan"],
    ["月矩力", "Kuuvahki"],
    ["有可莉", "có Klee"],
    ["朗姆罗", "Rumlow"],
    ["木叶丸", "Konohamaru"],
    ["木老师", "Kamiya lão sư"],
    ["本叔叔", "Uncle Ben"],
    ["朱诺市", "Juneau"],
    ["杀人脑", "MODOK"],
    ["权戒者", "Power Ring"],
    ["李洛克", "Rock Lee"],
    ["杜拉夫", "Draff"],
    ["来福枪", "Rifle"],
    ["杰罗麦", "Jerome"],
    ["枫原家", "Kaedehara gia"],
    ["枯木喉", "Ebony Maw"],
    ["柚木人", "Yugito"],
    ["查克拉", "Chakra"],
    ["查尔斯", "Charles"],
    ["查斯特", "Chester"],
    ["柯妮思", "Conis"],
    ["柯尔沃", "Culver"],
    ["格列佛", "Gulliver"],
    ["格蕾丝", "Grace"],
    ["格蕾尔", "Grail"],
    ["格雷尔", "Grail"],
    ["格雷森", "Grayson"],
    ["格鲁特", "Groot"],
    ["桑多涅", "Sandrone"],
    ["梅丽娜", "Melina"],
    ["梅加腊", "Megara"],
    ["梅卡罗", "Megalo"],
    ["梅帕克", "May Parker"],
    ["梅琳达", "Melinda May"],
    ["梦之树", "Cây Mộng Mơ"],
    ["梦蒂法", "Montifa"],
    ["森信郎", "Noburo Mori"],
    ["森林書", "Aranyaka"],
    ["欧尼桑", "Onii-san"],
    ["欧洛伦", "Ororon"],
    ["欧米加", "Omega"],
    ["欧罗巴", "Europa"],
    ["武士刀", "Katana"],
    ["死亡女", "Lady Deathstrike"],
    ["比邻星", "Proxima"],
    ["毛淡棉", "Mawlamyine"],
    ["水之国", "Thủy Quốc"],
    ["水户门", "Mitokado"],
    ["水无月", "Minatsuki"],
    ["水溅跃", "Splash"],
    ["永久卡", "vĩnh cửu tạp"],
    ["永恒族", "Eternals"],
    ["汉尼拨", "Hannibal"],
    ["汤之国", "Thang Quốc"],
    ["汤普森", "Thompson"],
    ["沃密尔", "Vormir"],
    ["沃辛顿", "Worthington"],
    ["沙忍村", "Làng Cát"],
    ["沙隐村", "Làng Cát"],
    ["沫芒宫", "Palais Mermonia"],
    ["油豆腐", "đậu phụ rán"],
    ["治疗术", "Hồi Máu"],
    ["法尔伽", "Varka"],
    ["法尔曾", "Falzone"],
    ["法师王", "pháp sư Wong"],
    ["法温德", "Fairwind"],
    ["波尔森", "Borson"],
    ["波旬信", "Uchiha Shin"],
    ["泰佐洛", "Tesoro"],
    ["泰坦星", "Titan tinh"],
    ["泰诺斯", "Thanos"],
    ["泷之国", "Lang Quốc"],
    ["泽拉斯", "Xerath"],
    ["洛克李", "Rock Lee"],
    ["津奈美", "Tsunami"],
    ["派斯克", "Paiske"],
    ["流浪者", "Wanderer"],
    ["浅濑响", "Asase Hibiki"],
    ["浮空塔", "phù không tháp"],
    ["海德拉", "Hydra"],
    ["海扁王", "Kick-Ass"],
    ["海祇岛", "Watatsumi đảo"],
    ["海祈岛", "Watatsumi đảo"],
    ["海祗岛", "Watatsumi đảo"],
    ["海芭夏", "Haypasia"],
    ["涅迦尔", "Nergal"],
    ["涡之国", "Oa Quốc"],
    ["淌津姬", "Tagitsuhime"],
    ["清迈府", "Tỉnh Chiang Mai"],
    ["温妮莎", "Vennessa"],
    ["湍津姬", "Tagitsu-hime"],
    ["滑板鞋", "Kalista"],
    ["满大人", "Mandarin"],
    ["潘多拉", "Pandora"],
    ["火之国", "Hỏa Quốc"],
    ["火之都", "Hỏa chi đô"],
    ["火巨人", "Hỏa cự nhân"],
    ["火玄间", "Shiranui Genma"],
    ["灯塔国", "Hoa Kỳ"],
    ["灵善坊", "Reizenbou"],
    ["灵矩关", "Thần Luật Quan"],
    ["炸弹人", "Ziggs"],
    ["照美冥", "Terumi Mei"],
    ["熊之国", "nước Nga"],
    ["爱丽丝", "Alice"],
    ["爱徳琳", "Adelinde"],
    ["爱德华", "Edward"],
    ["爱德琳", "Adelinde"],
    ["特卡查", "TChaka"],
    ["特工梅", "Agent May"],
    ["特拉男", "Trafalgar"],
    ["特瓦林", "Dvalin"],
    ["特瓦领", "Dvalin"],
    ["狂死郎", "Denjiro"],
    ["狐斋宫", "Kitsune Saiguu"],
    ["狮子狗", "Rengar"],
    ["猎鹿人", "Thợ săn hươu"],
    ["猕猴桃", "kiwi"],
    ["猪鹿蝶", "Ino-Shika-Cho"],
    ["玄间则", "Genma"],
    ["玖辛奈", "Kushina"],
    ["玛丽乔", "Mary Geoise"],
    ["玛丽简", "Mary Jane"],
    ["玛卡斯", "St. Marcus"],
    ["玛拉妮", "Mualani"],
    ["玛薇卡", "Mavuika"],
    ["珍妮特", "Janet"],
    ["珍宝女", "Jewel"],
    ["班尼特", "Bennett"],
    ["理查兹", "Richards"],
    ["琳尼特", "Lynette"],
    ["琴格雷", "Jean Grey"],
    ["琴葛蕾", "Jean Grey"],
    ["琺露珊", "Faruzan"],
    ["瑞克多", "Rictor"],
    ["瑟庄妮", "Sejuani"],
    ["瑟蕾莎", "Cereza"],
    ["璃月了", "Liyue"],
    ["璃月人", "Liyue người"],
    ["瓦夷帕", "Berserker"],
    ["瓦尔德", "World"],
    ["瓦特林", "Dvalin"],
    ["甘福尔", "Ganfor"],
    ["生論派", "Amurta"],
    ["生论派", "Amurta"],
    ["由木人", "Yugito"],
    ["电磁学", "điện từ học"],
    ["疯帽人", "Jervis Tetch"],
    ["疾风传", "Naruto"],
    ["白兰度", "Brando"],
    ["白夜国", "Enkanomiya quốc"],
    ["白皇后", "White Queen"],
    ["白矮星", "White Dwarf"],
    ["百目鬼", "Domeki"],
    ["皇后区", "The Queen"],
    ["皮士奇", "Pietro"],
    ["皮尔斯", "Pierce"],
    ["皮毛族", "Mink tộc"],
    ["皮耶罗", "Pierro"],
    ["皮耶羅", "Pierro"],
    ["盗宝团", "Đạo Bảo Đoàn"],
    ["真空刃", "Shinkūjin"],
    ["眼狩令", "Lệnh truy lùng Vision"],
    ["知論派", "Haravatat"],
    ["短生种", "đoản sinh chủng"],
    ["石头人", "Malphite"],
    ["砂之国", "Sa Quốc"],
    ["砂忍村", "Làng Cát"],
    ["砂隐村", "Làng Cát"],
    ["硝化银", "silver nitrate"],
    ["碧水源", "Bích Thủy Nguyên"],
    ["祖国人", "Homelander"],
    ["神之眼", "Vision"],
    ["神无家", "Kannazuka"],
    ["神秘客", "Mysterio"],
    ["神速力", "Speed Force"],
    ["福音帮", "Gospel Gang"],
    ["科勒曼", "Kellerman"],
    ["科拉斯", "Korath"],
    ["科莫多", "Komodo"],
    ["科萨语", "Xhosa ngữ"],
    ["科鲁兹", "Cruze"],
    ["稻草人", "Scarecrow"],
    ["第七班", "Đội 7"],
    ["第四代", "Đệ Tứ"],
    ["笹百合", "Sasayuri"],
    ["简泰克", "Gentek"],
    ["简福斯", "Jane · Foster"],
    ["米兰诺", "Milano"],
    ["米涅瓦", "Minn-Erva"],
    ["米琪塔", "Mikita"],
    ["米诺兰", "Benatar"],
    ["米雪儿", "Michelle"],
    ["类魔法", "loại ma pháp"],
    ["素论派", "Spantamad"],
    ["索拉卡", "Soraka"],
    ["紫阳花", "Ajisai"],
    ["維摩莊", "Vimara làng"],
    ["綺良良", "Kirara"],
    ["红发的", "Tóc Đỏ"],
    ["红坦克", "Juggernaut"],
    ["红头罩", "Red Hood"],
    ["红房子", "Red Room"],
    ["红水晶", "Hồng Ngọc"],
    ["红薯派", "bánh khoai lang"],
    ["红骷髅", "Red Skull"],
    ["约翰逊", "Johnson"],
    ["约里克", "Yorick"],
    ["纳塔鲁", "Natalu"],
    ["纳奇丝", "Natchios"],
    ["纳西妲", "Nahida"],
    ["终末番", "Sumatsuban"],
    ["绝云间", "Tuyệt Vân Gián"],
    ["绮良良", "Kirara"],
    ["绯木村", "Higi làng"],
    ["维克兹", "Velkoz"],
    ["维克多", "Victor"],
    ["维克托", "Viktor"],
    ["维山帝", "Vishanti"],
    ["维山蒂", "Vishanti"],
    ["维达尔", "Vidal"],
    ["绿灯侠", "Green Lantern"],
    ["绿灯戒", "green lantern"],
    ["绿箭侠", "Green Arrow"],
    ["绿青葵", "Rokushou Aoi"],
    ["罗伯特", "Robert"],
    ["罗德尼", "Rodney"],
    ["罗森桥", "Rosen Bridge"],
    ["罗琳娜", "Lorena"],
    ["罗生门", "Rashōmon"],
    ["美利坚", "America"],
    ["美露莘", "Melusine"],
    ["羯罗王", "Nagamasa"],
    ["老年斑", "lão niên Madara"],
    ["耕三郎", "Kozaburo"],
    ["肖尔斯", "Shales"],
    ["腹语人", "Ventriloquist"],
    ["自助餐", "Buffet"],
    ["自来也", "Jiraiya"],
    ["自由国", "Hoa Kỳ"],
    ["至圣所", "Sanctum Sanctorum"],
    ["良快刀", "Ryō Wazamono"],
    ["艾克恩", "Ikonn"],
    ["艾尔莎", "Elsa"],
    ["艾曼德", "Adamantium"],
    ["艾特沃", "Atwell"],
    ["艾瑞克", "Erik"],
    ["艾米克", "Amick"],
    ["艾芙娜", "Avna"],
    ["艾贾克", "Ajak"],
    ["芙兰佩", "Flampe"],
    ["芙宁娜", "Furina"],
    ["芙罗拉", "Flora"],
    ["芭別爾", "Babel"],
    ["芭别尔", "Babel"],
    ["芭芭拉", "Barbara"],
    ["花之间", "Empty Throne"],
    ["花散里", "Kazari"],
    ["苏克雷", "Sucre"],
    ["苏尔特", "Surtur"],
    ["苗瓦迪", "Myawaddy"],
    ["若娜瓦", "Ronova"],
    ["草丛伦", "Garen"],
    ["草忍村", "Thảo ẩn thôn"],
    ["草薙剑", "Kusanagi"],
    ["草隐村", "Thảo ẩn thôn"],
    ["荒原狼", "Steppenwolf"],
    ["药师兜", "Yakushi Kabuto"],
    ["莉奈娅", "Linnea"],
    ["莫拉格", "Morag"],
    ["莫格星", "Morag tinh"],
    ["莫甘娜", "Morgana"],
    ["莫霍克", "Mohawk"],
    ["莱依拉", "Layla"],
    ["菅名山", "Kanna núi"],
    ["菊花信", "Xin Zhao"],
    ["菊花国", "Nhật Bản"],
    ["菲奥娜", "Fiora"],
    ["菲林斯", "Flins"],
    ["菲米尼", "Ferminet"],
    ["萍姥姥", "Bình mỗ mỗ"],
    ["萝莉控", "lolicon"],
    ["萨卡星", "Sakaar"],
    ["萨坦圣", "St. Saturn"],
    ["萨斯给", "Sasuke"],
    ["萨琳娜", "Serleena"],
    ["萨诺斯", "Thanos"],
    ["葛瑞丝", "Grace"],
    ["葛罗丽", "Glory"],
    ["蒂亚姆", "Tiamut"],
    ["蒂亚穆", "Tiamut"],
    ["蒙巴顿", "Mountbatten"],
    ["蒸汽鸟", "Steam Bird"],
    ["蓝水晶", "Lam Ngọc"],
    ["蔓蒂丝", "Mantis"],
    ["蘭伊舍", "Araesha"],
    ["蘭利遮", "Ararycan"],
    ["蘭拉迦", "Araja"],
    ["蘭羅摩", "Arama"],
    ["蘭羯磨", "Arakarman"],
    ["蘭貢迪", "Arakunti"],
    ["蘭陀娑", "Aradasa"],
    ["蛤蟆丸", "Gamamaru"],
    ["蛤蟆吉", "Gamakichi"],
    ["蜘蛛女", "Spider-Woman"],
    ["蝙蝠侠", "Batman"],
    ["蝙蝠洞", "Batcave"],
    ["蝙蝠灯", "Batlight"],
    ["血之池", "Chinoike"],
    ["血龙眼", "Ketsuryūgan"],
    ["被打断", "bị đánh gãy"],
    ["西亚德", "Siad"],
    ["西奥多", "Theodore"],
    ["西尔弗", "Silver"],
    ["西恩娜", "Sinthia"],
    ["西格德", "Sigurd"],
    ["西海岸", "West Coast"],
    ["西索恩", "Chthon"],
    ["西索文", "Chthon"],
    ["西索斯", "Chthon"],
    ["西蒙斯", "Simmons"],
    ["观察者", "The Watchers"],
    ["詹姆斯", "James"],
    ["誓言岬", "Đỉnh lời thề"],
    ["護世森", "Lokapala đại sâm lâm"],
    ["请冷静", "xin tỉnh táo"],
    ["诺奇高", "Nojiko"],
    ["诺艾尔", "Noelle"],
    ["谢泼德", "Shepherd"],
    ["贝纳塔", "Benatar"],
    ["贝里克", "Bellick"],
    ["费拉德", "Vlad"],
    ["费舍尔", "Fisher"],
    ["贾克斯", "Jax"],
    ["贾维斯", "Jarvis"],
    ["赛丽娜", "Selena"],
    ["赛索斯", "Sethos"],
    ["赤胴铠", "Akato Yoroi"],
    ["赤铜铠", "Akadō Yoroi"],
    ["赤龙劫", "Xích Long Kiếp"],
    ["赫乌莉", "Havria"],
    ["赫莲娜", "Helena"],
    ["超人系", "Paramecia"],
    ["超女王", "Super-Woman"],
    ["超越者", "Beyonder"],
    ["路西法", "Lucifer"],
    ["踏鞴砂", "Tatarasuna"],
    ["轮回眼", "Rinnegan"],
    ["轴心国", "Đức quốc xã"],
    ["辛久奈", "Kushina"],
    ["辛吉德", "Singed"],
    ["达兹那", "Tazuna"],
    ["达尼拉", "Danila"],
    ["达达鸭", "Chúa hề"],
    ["迅猛龙", "Velociraptor"],
    ["迈勒斯", "Miles"],
    ["迈特凯", "Maito Gai"],
    ["迈阿密", "Miami"],
    ["迪埃斯", "Drake"],
    ["迪奥娜", "Diona"],
    ["迪希雅", "Dehya"],
    ["迪贝瑞", "DBari"],
    ["迪达拉", "Deidaira"],
    ["逐月节", "Trục Nguyệt Tiết"],
    ["遗留者", "He Who Remains"],
    ["那刻晴", "cái kia Keqing"],
    ["那撸多", "Naruto"],
    ["那瑟斯", "Nerthus"],
    ["郎姆洛", "Rumlow"],
    ["酒蒙子", "tửu quỷ"],
    ["重力鎓", "Gravitonium"],
    ["野伏众", "đám cường đạo"],
    ["野原琳", "Nohara Rin"],
    ["金克丝", "Jinx"],
    ["金刚狼", "Wolverine"],
    ["金字塔", "Pyramid"],
    ["金毘罗", "Kompira"],
    ["金钢狼", "Wolverine"],
    ["銚子市", "Chōshi thành phố"],
    ["钟离的", "Zhongli"],
    ["钢子铁", "Kotetsu"],
    ["钢铁侠", "Iron Man"],
    ["钢骨空", "Kong"],
    ["钯元素", "Palladium"],
    ["钷金属", "promethium metal"],
    ["铁之国", "Thiết Quốc"],
    ["银影侠", "Silver Surfer"],
    ["银武士", "Silver Samurai"],
    ["长十郎", "Chōjūrō"],
    ["长曾弥", "Nagasone"],
    ["长野原", "Naganohara"],
    ["长面包", "Streusen"],
    ["阿佩普", "Apep"],
    ["阿修罗", "Ashura"],
    ["阿兹尔", "Azir"],
    ["阿加莎", "Agatha"],
    ["阿卡丽", "Akali"],
    ["阿尔宁", "Arnim"],
    ["阿扎尔", "Azar"],
    ["阿拉冈", "Aragon"],
    ["阿拉科", "Arakko"],
    ["阿摩戈", "Amogotto"],
    ["阿斯加", "Asgard"],
    ["阿波罗", "Apollo"],
    ["阿瑞斯", "Ares"],
    ["阿舍鲁", "Ashru"],
    ["阿莎加", "Agatha"],
    ["阿萨佐", "Azazel"],
    ["阿萨姆", "Arnim"],
    ["阿贝多", "Albedo"],
    ["阿贾克", "Ajak"],
    ["阿迈德", "Ahmed"],
    ["陀龙王", "Azhdaha long vương"],
    ["隐型女", "Invisible Woman"],
    ["雅典娜", "Athena"],
    ["雅柯达", "Jahoda"],
    ["雨之国", "Vũ Quốc"],
    ["雨忍村", "Vũ nhẫn thôn"],
    ["雨隐村", "Làng Mưa"],
    ["雪之国", "Tuyết Quốc"],
    ["雷之国", "Lôi Quốc"],
    ["雷元素", "Lôi nguyên tố"],
    ["雷克托", "Rictor"],
    ["雷克顿", "Renekton"],
    ["雷兜王", "Vua Giáp Lôi"],
    ["雷电影", "Raiden Ei"],
    ["雷电真", "Raiden Makoto"],
    ["雷神影", "Raiden Ei"],
    ["雷耶斯", "Reyes"],
    ["雷霄古", "Ras al Ghul"],
    ["雾影村", "Làng Sương Mù"],
    ["雾忍村", "Làng Sương Mù"],
    ["霍利斯", "Hollis"],
    ["霍古名", "Homing"],
    ["霍尔斯", "Hvolsvöllur"],
    ["霍德华", "Howard"],
    ["霍比特", "Hobbit"],
    ["霜月村", "Shimotsuki thôn"],
    ["霸天虎", "Decepticon"],
    ["非米尼", "Freminet"],
    ["韦鲁斯", "Varus"],
    ["音隐村", "Làng Âm Thanh"],
    ["风流债", "phong lưu nợ"],
    ["风纪官", "Matra"],
    ["风车菊", "Cúc cánh quạt"],
    ["风速侠", "Whizzer"],
    ["饮血剑", "Huyết Kiếm"],
    ["马克思", "Marx"],
    ["马利克", "Malick"],
    ["马奇诺", "Machino"],
    ["马律师", "Matt luật sư"],
    ["马斯克", "Musk"],
    ["马维尔", "Marvell"],
    ["马苏卡", "Masoka"],
    ["马达拉", "Madara"],
    ["骨裂的", "gãy xương"],
    ["鬼童丸", "Kidomaru"],
    ["魔斯拉", "Mothra"],
    ["鲁斯坦", "Rostam"],
    ["鲍厄里", "Bowery"],
    ["鸣神岛", "Narukami đảo"],
    ["鹰司家", "Takatsukasa gia"],
    ["鹿野院", "Shikanoin"],
    ["麻布依", "Mabui"],
    ["麻布衣", "Mabui"],
    ["黄蜂女", "Wasp"],
    ["黄金乡", "Golden Belfry Bell"],
    ["黄金周", "Goldenweek"],
    ["黑凤凰", "Dark Phoenix"],
    ["黑刀夜", "Hắc Đao Yoru"],
    ["黑塔帮", "Black Tower Gang"],
    ["黑寡妇", "Black Widow"],
    ["黑心魔", "BlackHeart"],
    ["黑死剑", "Black Death Sword"],
    ["黑白绝", "Hắc Bạch Zetsu"],
    ["黑皇帝", "Black King"],
    ["黑矮星", "Black Dwarf"],
    ["黑蝠王", "Black Bolt"],
    ["黑麟病", "Eleazar bệnh"],
    ["黛布拉", "Debra"],
    ["龙之介", "Ryunosuke"],
    ["龙卷风", "Tornado"],
    ["龙地洞", "Ryuchi hang động"],
    ["龙脸上", "Dragon trên mặt"],
    ["一本贯手", "Ippon Nukite"],
    ["一脸笑容", "nở nụ cười"],
    ["一起吃顿", "cùng nhau ăn bữa"],
    ["万格达山", "Wundagore núi"],
    ["万物之下", "One Below All"],
    ["万达格山", "Wundagore núi"],
    ["三代火影", "Hokage Đệ Tam"],
    ["三代风影", "Kazekage đệ tam"],
    ["三相之力", "Tam Hợp Kiếm"],
    ["上帝保佑", "God bless"],
    ["不朽之城", "bất hủ chi thành"],
    ["丘丘暴徒", "Mitachurl"],
    ["丘丘萨满", "Samachurls"],
    ["中东战争", "Trung Đông chiến tranh"],
    ["中城高中", "Midtown High School"],
    ["丸星古介", "Maruboshi Kosuke"],
    ["丹内阿人", "Achaeans người"],
    ["主治医生", "bác sĩ trưởng"],
    ["乌克萨斯", "Uxas"],
    ["乔伊波伊", "Joy Boy"],
    ["二木由人", "Nii Yugito"],
    ["亚历山大", "Alexander"],
    ["亚托克斯", "Aatrox"],
    ["亡刃将军", "Corvus Glaive"],
    ["亲手打造", "tự tay chế tạo"],
    ["人人果实", "Hito Hito no Mi"],
    ["人道主义", "chủ nghĩa nhân đạo"],
    ["仙麟守月", "Tiên Lân Thủ Nguyệt"],
    ["以太精魂", "Hồn Ma Lạc Lỏng"],
    ["伊丽亚娜", "Illyana"],
    ["伊丽莎白", "Elizabeth"],
    ["伊凡万科", "Ivan Vanko"],
    ["伊斯塔露", "Istaroth"],
    ["伊泽瑞尔", "Ezreal"],
    ["伊瓦诺拉", "Evanora"],
    ["伊蒙洛卡", "Imunlaukr"],
    ["伊赞巴隆", "Ethanbaron"],
    ["伊邪纳岐", "Izanagi"],
    ["伐护末那", "Vahumana"],
    ["伟大航路", "Grand Line"],
    ["低语森林", "Thì Thầm rừng rậm"],
    ["佐敦海姆", "Jötunheimr"],
    ["佩珀代因", "Pepperdine"],
    ["佩露薇利", "Peruere"],
    ["倒退果实", "Modo Modo no Mi"],
    ["光明骑士", "Bright Knight"],
    ["光月家族", "Kouzuki gia tộc"],
    ["克吕莫涅", "Clineter"],
    ["克拉丽丝", "Clarce"],
    ["克拉格林", "Kraglin"],
    ["克拉科亚", "Krakoa"],
    ["克洛琳德", "Clorinde"],
    ["克洛罗斯", "Cronos"],
    ["克洛诺斯", "Khronos"],
    ["克莉丝汀", "Christine"],
    ["克里俄斯", "Crius"],
    ["克里斯汀", "Christine"],
    ["克里特岛", "đảo Crete"],
    ["八卦封印", "Hakke Fuin"],
    ["六道仙人", "Lục Đạo Tiên Nhân"],
    ["兰博基尼", "Lamborghini"],
    ["兰帕卡提", "Arapacati"],
    ["兰百梨迦", "Arabalika"],
    ["共杀灰骨", "Tomogoroshi no Haikotsu"],
    ["冈萨雷斯", "Gonzalez"],
    ["军情五处", "MI5"],
    ["冥王雷利", "Minh Vương Rayleigh"],
    ["冥界海姆", "Helheim"],
    ["冰川护甲", "Khiên Mãnh Sư"],
    ["冰脉护手", "Găng Tay Băng Giá"],
    ["冰萤术士", "Thuật sĩ Cicin băng"],
    ["冰霜之心", "Tim Băng"],
    ["冰霜之锤", "Búa Băng"],
    ["凝光大人", "Ningguang đại nhân"],
    ["凡尔科内", "Falcone"],
    ["刀锋战士", "Blade"],
    ["初代鬼彻", "Shodai Kitetsu"],
    ["利露帕尔", "Liloupar"],
    ["刹诃伐罗", "Kshahrewar"],
    ["刺客联盟", "The Fraternity"],
    ["前进基地", "tiền tuyến căn cứ"],
    ["剎訶伐羅", "Kshahrewar"],
    ["加具土命", "Kagutsuchi"],
    ["加州大学", "University of California"],
    ["加芙列拉", "Gabriela"],
    ["动手打她", "động thủ đánh nàng"],
    ["劳斯来斯", "Rolls Royce"],
    ["劳斯莱斯", "Rolls-Royce"],
    ["北欧阿萨", "Bắc Âu Aesir"],
    ["十万伏特", "Thunderbolt"],
    ["千手一族", "Senju nhất tộc"],
    ["千手板间", "Senju Itama"],
    ["千手柱间", "Senju Hashirama"],
    ["千手桃间", "Senju Tōka"],
    ["千手绳树", "Senju Nawaki"],
    ["半藏大人", "Hanzo-sama"],
    ["华纳神族", "Vanir thần tộc"],
    ["单体宇宙", "đơn thể vũ trụ"],
    ["南贺神社", "Naka Shrine"],
    ["卡塔琳娜", "Katarina"],
    ["卡尔哀尔", "Kal-Il"],
    ["卡尔奈克", "Karnak"],
    ["卡尔尼拉", "Karnilla"],
    ["卡尔波夫", "Karpov"],
    ["卡尔科萨", "Carcosa"],
    ["卡尔莫度", "Baron Mordo"],
    ["卡尔萨斯", "Karthus"],
    ["卡拉索芬", "Karla Sofen"],
    ["卡拉艾尔", "Kara Zor-El"],
    ["卡泰玛姬", "Kamar Taj"],
    ["卡特琳娜", "Catarina"],
    ["卡玛巴卡", "Kamabakka"],
    ["卡玛泰基", "Kamar Taj"],
    ["卡玛泰姬", "Kamar-Taj"],
    ["卡玛泰极", "Kamar-Taj"],
    ["卡皮塔諾", "Capitano"],
    ["卡皮塔诺", "Capitano"],
    ["卡米达尔", "Camidal"],
    ["卡萨扎莱", "Alcazarzaray"],
    ["卡马泰姬", "Kamar Taj"],
    ["卯月夕颜", "Uzuki Yūgao"],
    ["印第安那", "Indiana"],
    ["卷轴蛤蟆", "Gerotora"],
    ["厄勒提亚", "Eileithyia"],
    ["厄勒梯亚", "Eileithyia"],
    ["厄尔巴索", "El Paso"],
    ["厄洛法特", "Lohefalter"],
    ["厄瑞珀斯", "Erebus"],
    ["历史本文", "Poneglyphs"],
    ["双手插兜", "hai tay cắm vào túi"],
    ["双生暗影", "Song Sinh Ma Quái"],
    ["受害人类", "thụ hại nhân loại"],
    ["可可西亚", "Cocoyasi"],
    ["史尔特尔", "Surtr"],
    ["史柯西斯", "Scorsese"],
    ["号令之旗", "Lá Cờ Zeke"],
    ["号角日报", "nhật báo Bugle"],
    ["各类魔法", "các loại ma pháp"],
    ["吞吞果实", "Baku Baku no Mi"],
    ["命运长河", "mệnh vận trường hà"],
    ["和达鲁伊", "cùng Darui"],
    ["咕啦啦啦", "Gu ra ra ra ra"],
    ["咧嘴一笑", "nhếch miệng nở nụ cười"],
    ["哈利波特", "Harry Potter"],
    ["哈姆纳塔", "Hamunaptra"],
    ["哈姆达尔", "Heimdall"],
    ["哈密奎特", "Hamiquet"],
    ["哈西辣妈", "Hashirama"],
    ["哥伦比娅", "Columbina"],
    ["哥倫比婭", "Columbina"],
    ["哥谭日报", "Gotham Daily"],
    ["唐克雷蒂", "Tancredi"],
    ["唤灵术士", "Hoán Linh thuật sĩ"],
    ["喜多三郎", "Kitasaburo"],
    ["嘉文四世", "JarvanIV"],
    ["嘛嘛嘛嘛", "Má ma ma mà"],
    ["四紫炎阵", "Shishi Enjin"],
    ["四赤阳阵", "Shiseki Yōjin"],
    ["四风守护", "Tứ Phong Thủ Hộ"],
    ["圣冈萨斯", "San Venganza"],
    ["圣凡冈萨", "San Venganza"],
    ["在渊下宫", "tại Enkanomiya"],
    ["在飞雷神", "tại Phi Lôi Thần"],
    ["地下之王", "King of the Underground"],
    ["地狱厨房", "Hells Kitchen"],
    ["坚不可摧", "không thể phá vỡ"],
    ["坚城果实", "Shiro Shiro no Mi"],
    ["坦普润斯", "Temperance"],
    ["埃博拉罕", "Abraham"],
    ["埃德蒙德", "Edmonton"],
    ["埃阿涅斯", "Aeneas"],
    ["塞尔维德", "Selvig"],
    ["塞托拉克", "Cyttorak"],
    ["墨菲斯托", "Mephisto"],
    ["墨西哥裔", "gốc Mexico"],
    ["夏露莉亚", "Shalulia"],
    ["夕日真红", "Yuuhi Shinku"],
    ["多元宇宙", "đa nguyên vũ trụ"],
    ["多兰之戒", "Nhẫn Doran"],
    ["多兰之盾", "Khiên Doran"],
    ["夜丰颂府", "Tỉnh Mae Hong Son"],
    ["大动干戈", "làm to chuyện"],
    ["大奥术师", "đại áo thuật sư"],
    ["大岛秀一", "Shuichi Oshima"],
    ["大慈树王", "Đại Vương Rukkhadevata"],
    ["大慈樹王", "Đại Vương Rukkhadevata"],
    ["大陆酒店", "Continental Hotel"],
    ["天动万象", "Bansho Tenin"],
    ["天津瓮星", "Amatsu-Mikaboshi"],
    ["天目十五", "Amenoma Tougo"],
    ["天目影打", "Amenoma Kageuchi"],
    ["天碍震星", "Tengai Shinsei"],
    ["天空之脊", "Xương Sống Thiên Không"],
    ["天空航母", "Thiên không mẫu hạm"],
    ["天谴博士", "Doctor Nemesis"],
    ["太阳气息", "thái dương khí tức"],
    ["奈良鹿丸", "Nara Shikamaru"],
    ["奥丁格外", "Odin phá lệ"],
    ["奥奇贤者", "Doctor Occult"],
    ["奥巴代亚", "Obadiah"],
    ["奥德里奇", "Aldrif"],
    ["奥摩斯港", "Ormos cảng"],
    ["奥罗巴斯", "Orobashi"],
    ["奥莉安娜", "Orianna"],
    ["奥迪尔斯", "Othrys"],
    ["女神之泪", "Nước Mắt Nữ Thần"],
    ["女绿巨人", "She-Hulk"],
    ["威切斯特", "Westchester"],
    ["威彻斯特", "Westchester"],
    ["孢子之术", "Hōshi no Jutsu"],
    ["宇宙大帝", "Unicron"],
    ["宇宙灵球", "Cosmic Orb"],
    ["宇宙神明", "vũ trụ thần minh"],
    ["宇智波信", "Uchiha Shin"],
    ["宇智波斑", "Uchiha Madara"],
    ["宇智波泉", "Uchiha Izumi"],
    ["宇智波班", "Uchiha Madara"],
    ["宇智波镜", "Uchiha Kagami"],
    ["守护天使", "Giáp Thiên Thần"],
    ["安东尼娅", "Antonia"],
    ["安图苏尔", "Antusur"],
    ["完美国度", "hoàn mỹ quốc độ"],
    ["室罗婆耽", "Haravatat"],
    ["室羅婆耽", "Haravatat"],
    ["家庭主妇", "Housewife"],
    ["密瑟能核", "Mystryl thạch"],
    ["富豪夫妻", "phú hào vợ chồng"],
    ["封火法印", "Fūka Hōin"],
    ["小克拉克", "tiểu Clark"],
    ["小卡拉米", "phế vật"],
    ["小夜时雨", "Shigure"],
    ["小麦克尔", "tiểu Michael"],
    ["少年泰坦", "Teen Titans"],
    ["尹卡瑞斯", "Ikaris"],
    ["尼克福瑞", "Nick Fury"],
    ["尼姑拉丝", "Nicholas"],
    ["尼达维勒", "Nidavellir"],
    ["层岩巨渊", "Vực Đá Sâu"],
    ["山中井野", "Yamanaka Ino"],
    ["山中信玄", "Yamanaka Shingen"],
    ["山城青叶", "Yamashiro Aoba"],
    ["崔丝塔娜", "Tristana"],
    ["左近右近", "Sakon&Ukon"],
    ["巨人腰带", "Đai Khổng Lồ"],
    ["巫妖之祸", "Song Kiếm Tai Ương"],
    ["巫术合剂", "Dược Phẩm Thuật Pháp"],
    ["巫毒博士", "Dr. Voodoo"],
    ["巴尔萨扎", "Balthazar"],
    ["巴尔迪哥", "Baltigo"],
    ["巴布泽尔", "Beelzebul"],
    ["巴纳巴斯", "Tsaritsa"],
    ["巴里艾伦", "Barry Allen"],
    ["布拉多克", "Braddock"],
    ["布拉斯基", "Bronsky"],
    ["布朗克斯", "Bronx"],
    ["布朗斯基", "Bronsky"],
    ["布朗普顿", "Brompton"],
    ["布鲁斯李", "Bruce Lee"],
    ["希尔特工", "Hill đặc công"],
    ["帕蒂莎兰", "Padisarah"],
    ["帕迪萨拉", "Padisarah"],
    ["席尔维格", "Selvig"],
    ["干柿鬼鲛", "Hoshigaki Kisame"],
    ["并足雷同", "Namiashi Raidō"],
    ["幸运妈妈", "Mama Fortuna"],
    ["幽夜净土", "Vương Đô U Ám"],
    ["幽灵果实", "Horo Horo no Mi"],
    ["幽灵疾步", "Tốc Hành"],
    ["底片先生", "Mr. Negative"],
    ["廷达瑞斯", "Tyndareus"],
    ["开始解析", "bắt đầu phân tích"],
    ["异类魔力", "dị chủng ma lực"],
    ["弗兰克林", "Franklin"],
    ["弗洛伊德", "Floyd"],
    ["强大超凡", "cường đại siêu phàm"],
    ["强尼快客", "Johnny Quick"],
    ["强烈反对", "cường liệt phản đối"],
    ["强者之心", "cường giả chi tâm"],
    ["影子果实", "Kage Kage no Mi"],
    ["影影果实", "Kage Kage no Mi"],
    ["彼得帕克", "Peter Parker"],
    ["征服者康", "Kang the Conqueror"],
    ["御屋城炎", "Oyashiro En"],
    ["御庭番众", "Oniwabanshū"],
    ["微笑装甲", "Sentinel armor"],
    ["德莱厄斯", "Darius"],
    ["德雷萨斯", "Dressrosa"],
    ["心灵能力", "tâm linh năng lực"],
    ["忍术博士", "nhẫn thuật tiến sĩ"],
    ["忍者足具", "Giày Ninja"],
    ["志村团藏", "Shimura Danzō"],
    ["怀特霍尔", "Whitehall"],
    ["性格温顺", "tính cách dịu dàng ngoan ngoãn"],
    ["恶政王却", "Abaro Pisaro"],
    ["恶魔法典", "Sách Quỷ"],
    ["悉般多摩", "Spantamad"],
    ["悬浮汽车", "Suspension Car"],
    ["惊奇四侠", "Fantastic Four"],
    ["惊奇女士", "Ms. Marvel"],
    ["惊奇女孩", "Ms. Marvel"],
    ["惊恶先生", "Mr. Sinister"],
    ["愤怒合剂", "Dược Phẩm Phẫn Nộ"],
    ["我日向家", "Hyuga gia"],
    ["戴克斯特", "Dexter"],
    ["手术果实", "Ope Ope no Mi"],
    ["扎斯先生", "Mister Zsasz"],
    ["托卡列夫", "Tokarev"],
    ["拉多米尔", "Radomir"],
    ["拉斯加德", "Asgard"],
    ["拉斯普廷", "Rasputin"],
    ["拉瑟福德", "Rutherford"],
    ["指导上忍", "Jōnin lão sư"],
    ["挪德卡莱", "Nod-Krai"],
    ["探测卫星", "vệ tinh do thám"],
    ["提亚马特", "Rìu Timat"],
    ["提玛乌斯", "Timaeus"],
    ["撒坦尼什", "Satannish"],
    ["故事之神", "The God of the Story"],
    ["斩草除根", "trảm thảo trừ căn"],
    ["斩首大刀", "Kubikiribōchō"],
    ["断了一只", "gãy một cái"],
    ["斯佩克特", "Spector"],
    ["斯塔克拉", "Strucker"],
    ["斯库亚德", "Squad"],
    ["斯库尔克", "Skurge"],
    ["斯拉夫人", "Slav"],
    ["斯特拉克", "Strucker"],
    ["斯莫威尔", "Smallville"],
    ["斯蒂威尔", "Stillwell"],
    ["斯蒂芬妮", "Stephanie"],
    ["新泽西州", "New Jersey"],
    ["方塔索斯", "Phantasus"],
    ["方舟箴言", "Ark Maxim"],
    ["旋涡水户", "Uzumaki Mito"],
    ["旋涡鸣人", "Uzumaki Naruto"],
    ["旗木佐云", "Hatake Sakumo"],
    ["旗木朔夘", "Hatake Sakumo"],
    ["旗木朔茂", "Hatake Sakumo"],
    ["无尽之刃", "Vô Cực kiếm"],
    ["无相之雷", "Lôi nguyên bản"],
    ["无限手套", "Infinity Gauntlet"],
    ["日向天藏", "Hyuga Tenzo"],
    ["日向日足", "Hyuga Hiashi"],
    ["日向花火", "Hyūga Hanabi"],
    ["日向雏田", "Hyuga Hinata"],
    ["日炎斗篷", "Giáp Lửa"],
    ["时间小姐", "Miss Minute"],
    ["时间果实", "Toki Toki no Mi"],
    ["明朗之靴", "Giày Khai Sáng"],
    ["易物变化", "Narikawari no Jutsu"],
    ["星球大战", "Star Wars"],
    ["晨曦酒庄", "Dawn tửu trang"],
    ["普切涅拉", "Pulcinella"],
    ["普拉斯达", "Proudstar"],
    ["普罗提诺", "Plotinus"],
    ["普隆尼亚", "Pulonia"],
    ["智慧末刃", "Đao Tím"],
    ["暴风之剑", "Kiếm B.F"],
    ["暴风前线", "Stormfront"],
    ["月光疾风", "Gekkō Hayate"],
    ["月光骑士", "MoonKnight"],
    ["木南杏奈", "Kiminami Anna"],
    ["木叶白牙", "Konoha Nanh Trắng"],
    ["木叶隐村", "Konoha"],
    ["木龙之术", "Mokuryū no Jutsu"],
    ["本格雷姆", "Ben Grimm"],
    ["杰森托德", "Jason Todd"],
    ["枸橘矢仓", "Karatachi Yagura"],
    ["查尔罗斯", "Charlos"],
    ["查耶维奇", "Tsarevich"],
    ["柳德米拉", "Lyudmila"],
    ["树界降临", "Jukai Kōtan"],
    ["格尔尼卡", "Guernica"],
    ["格斗技能", "Fighting Skills"],
    ["格温多林", "Gwendolyn"],
    ["格雷玛金", "Graymalkin"],
    ["格雷福斯", "Graves"],
    ["桓那蘭那", "Vanarana"],
    ["梅瑞狄斯", "Meredith"],
    ["梦想一心", "Mộng tưởng nhất tâm"],
    ["梨多梵谛", "Rtawahist"],
    ["梵天神系", "Phạn Thiên thần hệ"],
    ["梵格尔夫", "Vingólf"],
    ["棘刺背心", "Áo Gai"],
    ["槛槛果实", "Ori Ori no Mi"],
    ["橡胶果实", "Gomu Gomu no Mi"],
    ["次元宇宙", "thứ nguyên vũ trụ"],
    ["欧庇克莱", "Eclipse"],
    ["武器果实", "Buki Buki no Mi"],
    ["死亡之舞", "Vũ Điệu Tử Thần"],
    ["死亡女神", "Tử Vong nữ thần"],
    ["死亡射手", "Deadshot"],
    ["死亡风暴", "Deathstorm"],
    ["毒毒果实", "Doku Doku no Mi"],
    ["气喘吁吁", "thở hồng hộc"],
    ["氪星将军", "Krypton tướng quân"],
    ["水户门炎", "Mitokado Homura"],
    ["水谷静子", "Mizutani Shizuko"],
    ["水银弯刀", "Đao Thủy Ngân"],
    ["水银饰带", "Khăn Giải Thuật"],
    ["汉克皮姆", "Hank Pym"],
    ["沃丘利圣", "St. Warcury"],
    ["沃利贝尔", "Volibear"],
    ["沙沙果实", "Suna Suna no Mi"],
    ["没人回答", "không ai hồi đáp"],
    ["油女志微", "Aburame Shibi"],
    ["治疗宝珠", "Ngọc Lục Bảo"],
    ["沼泽果实", "Numa Numa no Mi"],
    ["法尔克内", "Falkene"],
    ["法尔科尼", "Falcone"],
    ["法斯托斯", "Phastos"],
    ["波塞凡尼", "Persephanes"],
    ["波托马克", "Potomac"],
    ["波赛凡尼", "Persephone"],
    ["泰达米尔", "Tryndamere"],
    ["洗洗果实", "Woshu Woshu no Mi"],
    ["洛厄法特", "Lohefalter"],
    ["流浪武士", "Ronin"],
    ["海姆冥界", "Helheim"],
    ["海尔海姆", "Helheim"],
    ["海底出来", "đáy biển đi ra"],
    ["涡潮隐村", "Làng Uzumaki"],
    ["涨潮组织", "tổ chức Rising Tide"],
    ["深境螺旋", "La Hoàn Thâm Cảnh"],
    ["深渊面具", "Mặt Nạ Vực Thẳm"],
    ["深红恶魔", "thâm hồng ác ma"],
    ["演员工会", "SAG"],
    ["漩涡芦名", "Uzumaki Ashina"],
    ["漩涡长门", "Uzumaki Nagato"],
    ["漩涡鸣人", "Uzumaki Naruto"],
    ["潘塔涅夫", "Pantalone"],
    ["潘塔罗涅", "Pantalone"],
    ["潘塔羅涅", "Pantalone"],
    ["火箭浣熊", "Rocket gấu mèo"],
    ["灭霸天虎", "diệt Decepticon"],
    ["灵灵果实", "Horo Horo no Mi"],
    ["烟雾一族", "Iburi nhất tộc"],
    ["烧烧果实", "Mera Mera no Mi"],
    ["然德基尔", "Zadkiel"],
    ["燃烧宝石", "Hỏa Ngọc"],
    ["爆炸果实", "Bomu Bomu no Mi"],
    ["爆裂魔杖", "Gậy Bùng Nổ"],
    ["爱因斯坦", "Einstein"],
    ["特技演员", "đặc kỹ diễn viên"],
    ["特朗德尔", "Trundle"],
    ["犯罪之都", "Crime Capital"],
    ["犯罪集团", "Criminal Gang"],
    ["狂笑之蝠", "The Batman Who Laughs"],
    ["狼牙雪崩", "Nadare Roga"],
    ["猫猫果实", "Neko Neko no Mi"],
    ["猿飞未来", "Sarutobi Mirai"],
    ["玄月猎人", "Catarina Devon"],
    ["玛丽乔丹", "Mary Geoise"],
    ["玛丽大街", "Mary Street"],
    ["玛力乔亚", "Mary Geoise"],
    ["玛士撒拉", "Methuselah"],
    ["玛林福特", "Marineford"],
    ["玛格雷特", "Margaret"],
    ["玛莉卡塔", "Malikata"],
    ["环球日报", "Global Daily"],
    ["理山叠水", "Lý Thủy Điệp Sơn"],
    ["瓦尔哈尔", "Valhalla"],
    ["生化兵器", "sinh hóa binh khí"],
    ["生物质能", "sinh vật chất năng"],
    ["田心神姬", "Tagori-hime"],
    ["留风借云", "Lưu Phong Tá Vân"],
    ["疯狂攻击", "điên cuồng công kích"],
    ["疾射火炮", "Đại Bác Liên Thanh"],
    ["疾速追杀", "John Wick"],
    ["白云叶山", "Shirakumo Hayama"],
    ["白宫沦陷", "Nhà Trắng thất thủ"],
    ["白蛇仙人", "Hakuja Sennin"],
    ["白鹭公主", "Shirasagi Himegimi"],
    ["的卢皮卡", "Lupical"],
    ["相遇之緣", "Mối Duyên Tương Ngộ"],
    ["真实之眼", "Chân Thực Chi Nhãn"],
    ["瞪瞪果实", "Giro Giro no Mi"],
    ["矢岛正男", "Masao Yajima"],
    ["知无领域", "Knowhere"],
    ["石石果实", "Ishi Ishi no Mi"],
    ["砂隐忍者", "Ninja Làng Cát"],
    ["神乐心眼", "Kagura Shingan"],
    ["神奇先生", "Mister Fantastic"],
    ["神奇四侠", "Fantastic Four"],
    ["神无毗桥", "cầu Kannabi"],
    ["神月出云", "Kamizuki Izumo"],
    ["神樱大祓", "Anh Đào Thần"],
    ["神盾学院", "S.H.I.E.L.D học viện"],
    ["神里屋敷", "Kamisato lãnh địa"],
    ["福尔图娜", "Fortūna"],
    ["秋沙钱汤", "Aisa phòng tắm hơi"],
    ["科斯莫斯", "Kosmos"],
    ["科波帕特", "Cobblepot"],
    ["稻妻子民", "Inazuma người dân"],
    ["穆阿拉尼", "Mualani"],
    ["童趣果实", "Hobi Hobi no Mi"],
    ["米尔加德", "Midgard"],
    ["米德加德", "Midgard"],
    ["素烧之术", "Suyaki no Jutsu"],
    ["纠缠之缘", "Mối Duyên Vương Vấn"],
    ["红旗狄耶", "Red Flag X"],
    ["红桃妈妈", "Mama Hearts"],
    ["纲手公主", "Tsunade-hime"],
    ["纳什之牙", "Nanh Nashor"],
    ["纳摩瑞塔", "Namorita"],
    ["纳米战衣", "Nano-suit"],
    ["纳米机甲", "Nano Armor"],
    ["纳贝里士", "Naberius"],
    ["线线果实", "Ito Ito no Mi"],
    ["细思极恐", "tế tư cực khủng"],
    ["终结之谷", "chung kết chi cốc"],
    ["绝境计划", "Desperate Project"],
    ["绯红女巫", "Scarlet Witch"],
    ["维都利亚", "Victoria"],
    ["绿灯军团", "Green Lantern Corps"],
    ["罗兹瓦力", "Rosward"],
    ["罗曼诺夫", "Romanoff"],
    ["罗森桥的", "Rosen Bridge"],
    ["罗莎莉亚", "Rosalia"],
    ["罗马诺夫", "Romanoff"],
    ["罪恶之都", "City ​​of Sin"],
    ["美国队长", "Captain America"],
    ["群玉阁了", "Quần Ngọc Các"],
    ["老史塔克", "lão Stark"],
    ["耶梦加得", "Jörmungandr"],
    ["耶梦加德", "Jörmungandr"],
    ["肉球果实", "Nikyu Nikyu no Mi"],
    ["脸色铁青", "sắc mặt tái xanh"],
    ["腐败药水", "Bình Thuốc Biến Dị"],
    ["至尊太君", "Primacron"],
    ["舌根祸绝", "Zekka Konzetsu"],
    ["艾伦德林", "Arundolyn"],
    ["艾尔海森", "Alhaitham"],
    ["艾尼维亚", "Anivia"],
    ["艾梅莉埃", "Emilie"],
    ["艾爾海森", "Alhaitham"],
    ["艾瑞莉娅", "Irelia"],
    ["艾萨克斯", "Isaacs"],
    ["芙卡洛斯", "Focalors"],
    ["芭比洛斯", "Barbeloth"],
    ["芭芭雅嘎", "Baba Yaga"],
    ["花神诞日", "Lễ Hội Sabzeruz"],
    ["花花果实", "Hana Hana no Mi"],
    ["苏格拉底", "Socrate"],
    ["苯基乙氨", "Phenylethylamine"],
    ["茂盛果实", "Mosa Mosa no Mi"],
    ["范迪塞尔", "Vin Diesel"],
    ["茜特拉莉", "Citlali"],
    ["茜特菈琳", "Citlalin"],
    ["茜特菈莉", "Citlani"],
    ["莫尔甫斯", "Morpheus"],
    ["莫德凯撒", "Mordekaiser"],
    ["莫比乌斯", "Mobius"],
    ["莫比优斯", "Mobius"],
    ["莫比尤斯", "Mobius"],
    ["莫比迪亚", "Moby Dick"],
    ["莱欧斯利", "Wriothesley"],
    ["莱艮芬德", "Ragnvindr"],
    ["莱茵多特", "Rhinedottir"],
    ["菲利西亚", "Felicia"],
    ["菲尼克丝", "Phoenix"],
    ["菲尼克斯", "Phenex"],
    ["菲米斯特", "Phimister"],
    ["菲莉吉丝", "Ferigees"],
    ["萨塔斯基", "Sakazuki"],
    ["萨瓦迪卡", "Sawatdee Krab"],
    ["蒂玛乌斯", "Timaus"],
    ["蒸危暴威", "Jōki Bōi"],
    ["蒸危爆威", "Jōki Bōi"],
    ["蓝纹奶酪", "Blue Cheese"],
    ["蓬岳之野", "Autake lãnh địa"],
    ["藤虎一笑", "Fujitora Issho"],
    ["蘭帕卡提", "Arapacati"],
    ["蘭百梨迦", "Arabalika"],
    ["虚无之地", "Knowhere"],
    ["虚空之眼", "Vel’Koz"],
    ["蛋蛋伯爵", "Baron Tamago"],
    ["蜘蛛小子", "Spider-Boy"],
    ["蜘蛛战衣", "Spider-suit"],
    ["蝙蝠果实", "Batto Batto no Mi"],
    ["血继淘汰", "huyết kế đào thải"],
    ["血继限界", "huyết kế giới hạn"],
    ["血色之刃", "Huyết Đao"],
    ["血迹淘汰", "Kekkei Tōta"],
    ["血迹网罗", "Kekkei Mōra"],
    ["血迹限界", "huyết kế giới hạn"],
    ["血雾之里", "sương máu chính sách"],
    ["记忆果实", "Memo Memo no Mi"],
    ["许佩里翁", "Hyperion"],
    ["试作松籁", "Tiếng Gió Trong Rừng Thông"],
    ["请仙典仪", "Thỉnh Tiên Điển Lễ"],
    ["诸天神灵", "chư thiên Thần Linh"],
    ["诺提勒斯", "Nautilus"],
    ["诺曼诺夫", "Romanoff"],
    ["谍影重重", "The Bourne"],
    ["豪火灭失", "Gōka Messhitsu"],
    ["贝优妮塔", "Bayonetta"],
    ["贝优妮提", "Bayonetta"],
    ["贝希摩斯", "Behemoth"],
    ["贝拉斯特", "Bellas"],
    ["贝提斯塔", "Batista"],
    ["贝斯特拉", "Bestla"],
    ["贝纳塔克", "Benatar"],
    ["贪婪之刃", "Gươm Đồ Tể"],
    ["费德提克", "FiddleSticks"],
    ["赛博朋克", "Cyberpunk"],
    ["赛尼斯托", "Sinestro"],
    ["赛拉托克", "Cyttorak"],
    ["赛蒙托斯", "Ségur"],
    ["赤子之心", "xích tử chi tâm"],
    ["赤砂之蝎", "Akasuna no Sasori"],
    ["赫乌莉亚", "Havria"],
    ["赫尔姆特", "Helmut"],
    ["赫怀托斯", "Hephaestus"],
    ["超兽伪画", "Chōjū Giga"],
    ["超级小子", "Superboy"],
    ["超级英雄", "Super Hero"],
    ["车打芝士", "Cheddar Cheese"],
    ["转寝小春", "Utatane Koharu"],
    ["轮回天生", "Rinne Tensei"],
    ["轻灵之靴", "Giày Bạc"],
    ["辉夜一族", "Kaguya nhất tộc"],
    ["辉月一族", "Kaguya nhất tộc"],
    ["达克赛德", "Darkseid"],
    ["达纳多斯", "Thanatos"],
    ["达蒙内特", "Damonette"],
    ["达达鸭的", "Chúa hề"],
    ["达那都斯", "Thanatos"],
    ["远古冬棺", "Casket of Ancient Winters"],
    ["迟钝果实", "Noro Noro no Mi"],
    ["迪奥普斯", "Diops"],
    ["迪娜泽黛", "Dunyarzad"],
    ["迪娜澤黛", "Dunyarzad"],
    ["迭伊瓦希", "Iwashi Tatami"],
    ["速度之靴", "Giày Tăng Tốc"],
    ["達達利亞", "Tartaglia"],
    ["遗留之人", "He Who Remains"],
    ["那维莱特", "Neuvillete"],
    ["邪神教会", "Tà Thần giáo hội"],
    ["里斯托克", "Strucker"],
    ["金丝虾球", "Tôm Viên Tơ Vàng"],
    ["金属人体", "kim chúc hình người"],
    ["金属人型", "hình người kim loại"],
    ["金属人形", "hình người kim loại"],
    ["金杯酒吧", "Gold Cup Bar"],
    ["金缚之术", "Kanashibari no Jutsu"],
    ["金色闪光", "Tia Chớp Vàng"],
    ["金金果实", "Goru Goru no Mi"],
    ["钢钢果实", "Tetsu Tetsu no Mi"],
    ["钢铁之躯", "Man of Steel"],
    ["钢铁战衣", "Iron Suit"],
    ["铃木奈美", "Suzuki Nami"],
    ["铱星系统", "Iridium"],
    ["锡那罗亚", "Sinaloa"],
    ["锯齿短匕", "Dao Hung Tàn"],
    ["镀金旅团", "Eremite"],
    ["镇守之森", "rừng Chinju"],
    ["门捷列夫", "Mendeleev"],
    ["闪光果实", "Pika Pika no Mi"],
    ["阔落压路", "Konoyaro"],
    ["阿列克谢", "Aleksei"],
    ["阿勒德斯", "Allerdyce"],
    ["阿卡摩托", "Agamotto"],
    ["阿尔卡利", "Alkali"],
    ["阿布鲁奇", "Abruzzi"],
    ["阿弥利多", "Amurta"],
    ["阿彌利多", "Amurta"],
    ["阿戈摩多", "Agamotto"],
    ["阿扎赛尔", "Azazel"],
    ["阿托莫斯", "Agamotto"],
    ["阿拉斯加", "Alaska"],
    ["阿斯加德", "Asgard"],
    ["阿斯卡德", "Asgard"],
    ["阿斯玛代", "Asuma"],
    ["阿美丽卡", "America"],
    ["阿莲诺娃", "Alianovna"],
    ["阿蕾奇諾", "Arlecchino"],
    ["阿蕾奇诺", "Arlecchino"],
    ["阿贝多了", "Albedo"],
    ["阿赫玛尔", "Al-Ahmar"],
    ["阿里克斯", "Alex"],
    ["阿陀河谷", "Ardravi thung lũng"],
    ["雨之希留", "Shiliew"],
    ["雪之一族", "Minatsuki nhất tộc"],
    ["雷恩加尔", "Rengar"],
    ["雷斯罗萨", "Dressrosa"],
    ["雷犁热刀", "Rariatto"],
    ["雷电将军", "Raiden Shogun"],
    ["雷神大人", "Raiden Shogun"],
    ["雷萤术士", "Thuật sĩ Cicin lôi"],
    ["雷霄奥古", "Ras al Ghul"],
    ["震震果实", "Gura Gura no Mi"],
    ["霍尔金斯", "Hoskins"],
    ["霓裾翩跹", "Vũ điệu Nghê thường"],
    ["露娜利亚", "Lunarians"],
    ["青梅竹马", "thanh mai trúc mã"],
    ["面向对象", "Object Oriented"],
    ["靶靶果实", "Mato Mato no Mi"],
    ["鞍马八云", "Kurama Yakumo"],
    ["須彌薔薇", "Tường Vi Sumeru"],
    ["须左能乎", "Susanoo"],
    ["须弥蔷薇", "Tường Vi Sumeru"],
    ["风祭萌黄", "Kazamatsuri Moegi"],
    ["飞竹蜻蜓", "Tobitake Tonbo"],
    ["飞马计划", "Project Pegasus"],
    ["马克塔格", "MacTaggert"],
    ["马克战衣", "Mark chiến y"],
    ["马克系列", "Mark series"],
    ["马卡鲁峰", "núi Makalu"],
    ["马尔巴克", "Marbas"],
    ["马尔萨泽", "Balthazar"],
    ["马斯拉尼", "Masrani"],
    ["马林佛多", "Marineford"],
    ["马林福德", "Marineford"],
    ["马琳繁多", "Marineford"],
    ["马科修斯", "Marchosius"],
    ["马马果实", "Uma Uma no Mi"],
    ["驯龙高手", "How to Train Your Dragon"],
    ["高卢雄鸡", "nước Pháp"],
    ["高塔孤王", "Tháp Cô Vương"],
    ["魂魂果实", "Soru Soru no Mi"],
    ["魄罗投掷", "Ném Poro"],
    ["魔兽世界", "World of Warcraft"],
    ["魔鳞病的", "Eleazar bệnh"],
    ["鱼鱼果实", "Uo Uo no Mi"],
    ["鲁格手枪", "Luger súng ngắn"],
    ["鸥诺弥亚", "Eunomia"],
    ["鹿久等人", "Shikaku mọi người"],
    ["麋鹿大街", "Elk Street"],
    ["黄色闪光", "Tia Chớp Vàng"],
    ["黄金福袋", "Túi Vàng"],
    ["黑刀秋水", "Kokutō Shusui"],
    ["黑暗奇异", "hắc ám Dr. Strange"],
    ["黑暗封印", "Phong Ấn Hắc Ám"],
    ["黑暗神书", "Book of Darkness"],
    ["黑暗英雄", "Dark Hero"],
    ["黑暗骑士", "Dark Knight"],
    ["黑田编辑", "Kuroda biên tập"],
    ["黑皇帝肖", "Black King Shaw"],
    ["黑耀五将", "Black Order"],
    ["黑色太阳", "Black Sun"],
    ["黑默丁格", "Heimerdinger"],
    ["鼓舞果实", "Kobu Kobu no Mi"],
    ["龙脊雪山", "Long Tích Tuyết sơn"],
    ["龙龙果实", "Ryu Ryu no Mi"],
    ["万世催化石", "Đá Vĩnh Hằng"],
    ["万能的神明", "vạn năng thần minh"],
    ["三碗不过港", "Ba Cốc Say Mèm"],
    ["不死鸟果实", "Tori Tori no Mi"],
    ["不知火玄间", "Shiranui Genma"],
    ["丘丘人萨满", "Samachurls"],
    ["丘丘岩盔王", "Lawachurl nham"],
    ["二位由木人", "Nii Yugito"],
    ["亚尔伯里奇", "Alberich"],
    ["亚里士多德", "Aristotle"],
    ["伊万诺夫娜", "Ivanovna"],
    ["伊菲格涅娅", "Iphigenia"],
    ["伊阿伯托斯", "Labertus"],
    ["伊阿珀托斯", "Labertus"],
    ["佩特洛尼拉", "Petronilla"],
    ["俄克安诺斯", "Oceanus"],
    ["俄克阿诺斯", "Oceanus"],
    ["俄刻阿诺斯", "Oceanus"],
    ["克拉特鲁斯", "Craterus"],
    ["克留兹理德", "Kreuzlied"],
    ["克鲁兹希卡", "Kruzchka"],
    ["凡性的提醒", "Lời Nhắc Tử Vong"],
    ["加维奥塔斯", "Gaviota"],
    ["博格利亚斯", "BomGaliath"],
    ["博萨特之雷", "Bolts of Balthakk"],
    ["卡斯利亚斯", "Casillas"],
    ["卡斯柏管家", "Casper quản gia"],
    ["卡西利亚斯", "Casillas"],
    ["卡西里奥斯", "Kaecilius"],
    ["卡里西亚斯", "Calisias"],
    ["卢登的回声", "Vọng Âm Luden"],
    ["古伦希尔德", "Gunnhildr"],
    ["古恩希尔德", "Gunnhildr"],
    ["古罗莉欧萨", "Gloriosa"],
    ["吸血鬼节杖", "Huyết Trượng"],
    ["咆哮突击队", "Howling Commandos"],
    ["和平主义者", "Pacifista"],
    ["哨兵机器人", "Sentinel robot"],
    ["嚎叫突击队", "Howling Commandos"],
    ["国土安全局", "DHS"],
    ["国土安全部", "DHS"],
    ["圣母玛利亚", "Virgin Mary"],
    ["埃利萨里昂", "Ellisarion"],
    ["基克的聚合", "Điềm Báo Zeke"],
    ["墨涅拉奥斯", "Menelaus"],
    ["复用型药水", "Thuốc Tái Sử Dụng"],
    ["多弗拉明哥", "Doflamingo"],
    ["多弗朗明哥", "Doflamingo"],
    ["多德卡尼斯", "Dodekanisa"],
    ["多芙拉明哥", "Doflamingo"],
    ["大天使之杖", "Quyền Trượng Thiên Sứ"],
    ["大桐木辉夜", "Ōtsutsuki Kaguya"],
    ["大玉螺旋丸", "Odama Rasengan"],
    ["大筒木桃式", "Ōtsutsuki Momoshiki"],
    ["大筒木羽衣", "Ōtsutsuki Hagoromo"],
    ["大筒木芝居", "Ōtsutsuki Shibai"],
    ["奥克托维斯", "Otto Octavius"],
    ["始动的秒表", "Đồng Hồ Ngưng Đọng"],
    ["宇宙第一因", "《○》"],
    ["宇智波佐助", "Uchiha Sasuke"],
    ["宇智波八代", "Uchiha Yashiro"],
    ["宇智波刹那", "Uchiha Setsuna"],
    ["宇智波带土", "Uchiha Obito"],
    ["宇智波泉奈", "Uchiha Izuna"],
    ["宇智波美月", "Uchiha Mizuki"],
    ["宇智波美琴", "Uchiha Mikoto"],
    ["守望者铠甲", "Giáp Cuồng Đồ"],
    ["安全理事会", "UNSC"],
    ["安德洛玛克", "Andromache"],
    ["安德留斯高", "Andrius"],
    ["安格尔伯达", "Angrboda"],
    ["小吉祥草王", "Tiểu Vương Kusanali"],
    ["小罗宾根本", "tiểu Robin căn bản"],
    ["小辣椒佩珀", "Pepper Potts"],
    ["尼德维阿尔", "Nidavellir"],
    ["山椒鱼半藏", "Salamander Hanzō"],
    ["布拉德多福", "Bradford"],
    ["布拉德皮特", "Brad Pitt"],
    ["布鲁德海文", "Bludhaven"],
    ["希尔德加德", "Hildegard"],
    ["库胡勒阿乔", "Kuhul Ajaw"],
    ["弗拉基米尔", "Vladimir"],
    ["御手洗红豆", "Mitarashi Anko"],
    ["心转身之术", "tâm chuyển thân chi thuật"],
    ["我的上帝啊", "Oh my God"],
    ["托尼斯塔克", "Tony Stark"],
    ["拉托维尼亚", "Latovina"],
    ["拉格伽多尔", "Raggardor"],
    ["摩涅摩绪涅", "Mnemosyne"],
    ["斯卡拉姆齊", "Scaramouche"],
    ["斯卡拉姆齐", "Scaramouche"],
    ["斯塔克大厦", "Stark Building"],
    ["斯考菲尔德", "Scofield"],
    ["斯莱布尼尔", "Sleipnir"],
    ["方舟反应炉", "Arc Reactor"],
    ["旗木卡卡西", "Hatake Kakashi"],
    ["无上大快刀", "Saijō Ō Wazamono"],
    ["日不落帝国", "United Kingdom"],
    ["旧日支配者", "Great Old One"],
    ["普利阿莫斯", "Priam"],
    ["暗黑比邻星", "Proxima Midnight"],
    ["暴徒丘丘人", "Mitachurl"],
    ["暴虐迅猛龙", "Indoraptor"],
    ["望风山地的", "Vọng Phong sơn địa"],
    ["查尔罗斯圣", "Charlos thánh"],
    ["树王圣体菇", "Nấm Thánh Rukkhashava"],
    ["格兰德沃特", "Grand Ward"],
    ["格温史黛西", "Gwen Stacy"],
    ["梅吉斯图斯", "Megistus"],
    ["森乃伊比喜", "Morino Ibiki"],
    ["欧科塔维亚", "Octavia"],
    ["比弗罗斯特", "Bifrost"],
    ["永恒万花筒", "Eternal Mangekyou"],
    ["沃尔斯塔格", "Volstagg"],
    ["海克斯科技", "Súng Hextech"],
    ["海豹突击队", "SEALs"],
    ["消灭霸天虎", "tiêu diệt Decepticon"],
    ["混乱的时候", "thời điểm hỗn loạn"],
    ["漩涡玖幸奈", "Uzumaki Kushina"],
    ["火烧山等等", "Yamakaji"],
    ["炽天使之拥", "Quyền Trượng Đại Thiên Sứ"],
    ["特劳法尔加", "Trafalgar"],
    ["猎人克莱文", "Kraven the Hunter"],
    ["猩红百夫长", "Scarlet Centurion"],
    ["玛利亚希尔", "Maria Hill"],
    ["珠子的形状", "hình dáng hạt châu"],
    ["白胡子老头", "lão đầu râu bạc"],
    ["百无禁忌箓", "Bách vô cấm kỵ lục"],
    ["矢志田信玄", "Yashida Shingen"],
    ["知识的诅咒", "The Curse of Knowledge"],
    ["米尔科维奇", "Milkovich"],
    ["紫雨林之拳", "Nấm Đấm Jaurim"],
    ["纳斯寿郎圣", "St. Nusjuro"],
    ["维里甘之拳", "Fist of Verrigan"],
    ["罗德里格斯", "Rodríguez"],
    ["罗莎琳小姐", "Rosalyne tiểu thư"],
    ["至尊小超人", "Superboy-Prime"],
    ["艾尔登法环", "Elden Ring"],
    ["花树界降临", "Kajukai Kōrin"],
    ["药师野乃宇", "Yakushi Nonou"],
    ["莫扎伊斯克", "Mozhaysk"],
    ["莫涅莫绪涅", "Mnemosyne"],
    ["莫雷洛秘典", "Quỷ Thư Morello"],
    ["莱克斯卢瑟", "Lex Luthor"],
    ["菲利亚西亚", "Felicia"],
    ["菲尔戈黛特", "Verr Goldet"],
    ["螺旋手里剑", "RasenShuriken"],
    ["西瓜山河豚", "Suikazan Fuguki"],
    ["要塞恩加莱", "NGarai"],
    ["贝雅特里奇", "Beatrice"],
    ["贾巴里山脉", "Jabari sơn mạch"],
    ["赛巴斯蒂安", "Sebastian"],
    ["轮回写轮眼", "RinneSharingan"],
    ["辉夜君麻吕", "Kaguya Kimimaro"],
    ["达伦克劳斯", "Darren Cross"],
    ["近松十人众", "Jikki Chikamatsu no Shū"],
    ["速度与激情", "Fast and Furious"],
    ["金伦加世界", "Ginnungagap thế giới"],
    ["钢铁爱国者", "Iron Patriot"],
    ["银河滑翔者", "Silver Surfer"],
    ["银色冲浪者", "Silver Surfer"],
    ["银色滑翔者", "Silver Surfer"],
    ["长老会医院", "Presbyterian Hospital"],
    ["阿尔弗雷德", "Alfred"],
    ["阿拉巴斯坦", "Alabasta"],
    ["阿斯莫德斯", "Asmodeus"],
    ["阿玛耳忒亚", "Amalthea"],
    ["阿芙罗迪忒", "Aphrodite"],
    ["阿里瑟什么", "Arishem"],
    ["附魔：战士", "Phù Phép: Chiến Binh"],
    ["雪奈茨维奇", "Snezhevich"],
    ["雷克雅未克", "Reykjavík"],
    ["雷电将军了", "Raiden Shogun"],
    ["雷电将军的", "Raiden Shogun"],
    ["雾切之回光", "Ánh sáng đêm sương mù"],
    ["非凡复仇者", "Uncanny Avengers"],
    ["非裔女朋友", "gốc Phi bạn gái"],
    ["飞雷神之术", "Hiraishin no Jutsu"],
    ["马克西姆斯", "Maximoff"],
    ["马克西宙斯", "Maxie Zeus"],
    ["马西克莫夫", "Maximoff"],
    ["高岭昆布丸", "Takamine Konbumaru"],
    ["鬼芽罗之术", "Quỷ nha la chi thuật"],
    ["鹿野院平藏", "Shikanoin Heizou"],
    ["黄泉比良坂", "Yomotsu Hirasaka"],
    ["黑色玛丽亚", "Black Maria"],
    ["黑袍纠察队", "The Boys"],
    ["万花筒写轮眼", "Mangekyou Sharingan"],
    ["乔 · 艾尔", "Jor · El"],
    ["亚尔其蔓红树", "Yarukiman Mangrove"],
    ["俄克阿尼得斯", "Oceanid"],
    ["俄刻阿儀诺斯", "Oceanus"],
    ["八歧大蛇果实", "Hebi Hebi no Mi"],
    ["兰德里的折磨", "Đai Lưng Hextech"],
    ["削月筑阳真君", "Tước Nguyệt Trúc Dương Chân Quân"],
    ["努努和威朗普", "Nunu"],
    ["勇 · 罗格", "Yon Rogg"],
    ["卢安娜的飓风", "Cuồng Cung Runaan"],
    ["叮铃哐啷蛋卷", "Krumkake Clink-Clank"],
    ["土中映鱼之术", "Dochū Eigyo no Jutsu"],
    ["基舍艾斯碎片", "Mãnh Vỡ Kercheis"],
    ["大侦探皮卡丘", "Detective Pikachu"],
    ["好邻居蜘蛛侠", "Good Neighbor Spider-Man"],
    ["宇智波的祠堂", "Uchiha từ đường"],
    ["安拉胡阿克巴", "Allāhu Akbar"],
    ["恩 - 加莱", "Flickering"],
    ["情报历史本文", "Instructional Poneglyph"],
    ["托马 · 雷", "Tomar · Re"],
    ["拉基 · 鲁", "Lucky Roo"],
    ["拉奇 · 鲁", "Lucky Roo"],
    ["拉娜 · 蓝", "Lana · Lang"],
    ["斯塔缇克电刃", "Dao Điện Statikk"],
    ["斯瓦泰夫海姆", "Svartalfheim"],
    ["普恩特安提戈", "Puente Antiguo"],
    ["朗基努斯之枪", "Lance of Longinus"],
    ["杰伊戈路西亚", "Jaygarcia"],
    ["桑歌玛哈巴依", "Sangemah Bay"],
    ["梅贾的窃魂卷", "Sách Chiêu Hồn Mejai"],
    ["活力夹心饼干", "Bánh Bích Quy"],
    ["猎人的宽刃刀", "Đao Thợ Săn"],
    ["猎人的护身符", "Bùa Thợ Săn"],
    ["玛 · 威尔", "Mar-Vell"],
    ["玛丽 · 简", "Mary · Jane"],
    ["琴 · 葛蕾", "Jean Grey"],
    ["瓦特阿尔海姆", "Svartalfheim"],
    ["用自己的力量", "dùng sức mạnh của mình"],
    ["福兹 · 弗", "Who’s Who"],
    ["穆斯贝尔海姆", "Muspelheim"],
    ["细患抽出之术", "Saikan Chushutsu no Jutsu"],
    ["自业咒缚之印", "Jigō Jubaku no In"],
    ["良快刀五十工", "50 thanh Ryō Wazamono"],
    ["芝加哥大剧院", "Chicago Theater"],
    ["西瓜山河豚鬼", "Suikazan Fuguki"],
    ["赫尔斯特罗姆", "Hellström"],
    ["赫芙那梵因斯", "von Hrafnavins"],
    ["超轻重岩之术", "Chōkejūgan no Jutsu"],
    ["迈特 · 戴", "Maito Dai"],
    ["阿卡姆疯人院", "Arkham Asylum"],
    ["阿尔忒忒弥斯", "Artemis"],
    ["阿德剌斯忒亚", "Amalthea"],
    ["阿斯托洛吉斯", "Astrolabos"],
    ["阿美莉卡特工", "America đặc công"],
    ["韦斯特莫兰德", "Westmoreland"],
    ["黑刀 · 夜", "Hắc Đao Yoru"],
    ["发条精神病医院", "Clockwork Psychiatric Hospital"],
    ["大快刀二十一工", "21 thanh Ō Wazamono"],
    ["夺来的神谕精粹", "Chiết Xuất Oracle"],
    ["奥瑞利安·索尔", "AurelionSol"],
    ["少女飘摇的杀意", "Thiếu nữ đáng yêu"],
    ["布拉卡格伏特加", "Blackagar Boltagon"],
    ["微现的远见守卫", "Thấu Kính"],
    ["德拉克萨的暮刃", "Dạ Kiếm Dratharr"],
    ["斯科特 · 朗", "Scott · Lang"],
    ["普罗忒西拉奥斯", "Protesilaus"],
    ["梅琳达 · 梅", "Melinda May"],
    ["比尔吉沃特弯刀", "Gươm Hải Tặc"],
    ["海克斯科技枪刃", "Kiếm Súng Hextech"],
    ["玛莫提乌斯之噬", "Chùy Gai"],
    ["瓦特阿尔尔海姆", "Svartalfheim"],
    ["考尔菲德的战锤", "Búa Chiến Caufield"],
    ["舒瑞娅的狂想曲", "Vương Miện Shurelya"],
    ["达恩 - 加莱", "đến Flickering"],
    ["附魔：符能回声", "Phù Phép: Thần Vọng"],
    ["雷德 · 佛斯", "Red Force"],
    ["霍华德汽车公司", "Howard Motor Company"],
    ["鬼索的狂暴之刃", "Cuồng Đao Guinsoo"],
    ["亚马逊 · 百合", "Amazon Lily"],
    ["四分五裂恶魔果实", "Bara Bara no Mi"],
    ["圣胡安 · 恶狼", "Sanjuan Wolf"],
    ["无上大快刀十二工", "12 thanh Saijō Ō Wazamono"],
    ["春田 1903 ", "《Springfield 1903》"],
    ["永续意志夹心饼干", "Bánh Bích Quy"],
    ["沙鳄鱼克洛克达尔", "Sir Crocodile"],
    ["海克斯科技左轮枪", "Súng Hextech"],
    ["灭世者的死亡之帽", "Mũ Phù Thủy"],
    ["阿卡姆精神病医院", "Arkham Psychiatric Hospital"],
    ["Thank you", "Thank you"],
    ["塞巴斯蒂安 · 肖", "Sebastian Shaw"],
    ["尤利西斯 · 克劳", "Ulysses · Klaw"],
    ["沙 · 克洛克达尔", "Sir Crocodile"],
    ["绍沙 M1915 ", "《Chauchat M1915》"],
    ["巴洛里克 · 莱德菲尔德", "Patrick·Redfield"],
    ["塔利娅 · 艾尔 · 古尔", "Talia al Ghul"]
];
