load("config.js");

function execute(input) {
    var genres = [
        ["16+", "the-loai/16"],
        ["18+", "the-loai/18"],
        ["19+", "the-loai/19"],
        ["3D Hentai", "the-loai/3d-hentai"],
        ["3P", "the-loai/3p"],
        ["Action", "the-loai/action"],
        ["Adult", "the-loai/adult"],
        ["Adventure", "the-loai/adventure"],
        ["Ahegao", "the-loai/ahegao"],
        ["Anal", "the-loai/anal"],
        ["Angel", "the-loai/angel"],
        ["Ảnh động", "the-loai/anh-dong"],
        ["Animal", "the-loai/animal"],
        ["Animal girl", "the-loai/animal-girl"],
        ["Áo Dài", "the-loai/ao-dai"],
        ["Apron", "the-loai/apron"],
        ["Artist CG", "the-loai/artist-cg"],
        ["Based Game", "the-loai/based-game"],
        ["BBM", "the-loai/bbm"],
        ["BBW", "the-loai/bbw"],
        ["BDSM", "the-loai/bdsm"],
        ["Bestiality", "the-loai/bestiality"],
        ["Big Ass", "the-loai/big-ass"],
        ["Big Boobs", "the-loai/big-boobs"],
        ["Big Penis", "the-loai/big-penis"],
        ["Blackmail", "the-loai/blackmail"],
        ["Bloomers", "the-loai/bloomers"],
        ["BlowJobs", "the-loai/blowjobs"],
        ["Body Swap", "the-loai/body-swap"],
        ["Bodysuit", "the-loai/bodysuit"],
        ["Bondage", "the-loai/bondage"],
        ["Breast Sucking", "the-loai/breast-sucking"],
        ["BreastJobs", "the-loai/breastjobs"],
        ["Brocon", "the-loai/brocon"],
        ["Brother", "the-loai/brother"],
        ["Business Suit", "the-loai/business-suit"],
        ["Catgirls", "the-loai/catgirls"],
        ["Che ít", "the-loai/che-it"],
        ["Che nhiều", "the-loai/che-nhieu"],
        ["Cheating", "the-loai/cheating"],
        ["Chikan", "the-loai/chikan"],
        ["Chinese Dress", "the-loai/chinese-dress"],
        ["Chưa Phân Loại", "the-loai/chua-phan-loai"],
        ["Có che", "the-loai/co-che"],
        ["Comedy", "the-loai/comedy"],
        ["Comic", "the-loai/comic"],
        ["Con gái", "the-loai/con-gai"],
        ["Condom", "the-loai/condom"],
        ["Cosplay", "the-loai/cosplay"],
        ["Cousin", "the-loai/cousin"],
        ["Công Sở", "the-loai/cong-so"],
        ["Crotch Tattoo", "the-loai/crotch-tattoo"],
        ["Cunnilingus", "the-loai/cunnilingus"],
        ["Dark Skin", "the-loai/dark-skin"],
        ["Daughter", "the-loai/daughter"],
        ["Deepthroat", "the-loai/deepthroat"],
        ["Demon", "the-loai/demon"],
        ["DemonGirl", "the-loai/demongirl"],
        ["Devil", "the-loai/devil"],
        ["DevilGirl", "the-loai/devilgirl"],
        ["Dirty", "the-loai/dirty"],
        ["Dirty Old Man", "the-loai/dirty-old-man"],
        ["DogGirl", "the-loai/doggirl"],
        ["Double Penetration", "the-loai/double-penetration"],
        ["Doujinshi", "the-loai/doujinshi"],
        ["Drama", "the-loai/drama"],
        ["Drug", "the-loai/drug"],
        ["Đã full", "the-loai/da-full"],
        ["Ecchi", "the-loai/ecchi"],
        ["Echi", "the-loai/echi"],
        ["Elder Sister", "the-loai/elder-sister"],
        ["Elf", "the-loai/elf"],
        ["Exhibitionism", "the-loai/exhibitionism"],
        ["Fantasy", "the-loai/fantasy"],
        ["Father", "the-loai/father"],
        ["Femdom", "the-loai/femdom"],
        ["Fingering", "the-loai/fingering"],
        ["Footjob", "the-loai/footjob"],
        ["Foxgirls", "the-loai/foxgirls"],
        ["Full Color", "the-loai/full-color"],
        ["Furry", "the-loai/furry"],
        ["Futanari", "the-loai/futanari"],
        ["GangBang", "the-loai/gangbang"],
        ["Garter Belts", "the-loai/garter-belts"],
        ["Gender Bender", "the-loai/gender-bender"],
        ["Ghost", "the-loai/ghost"],
        ["Glasses", "the-loai/glasses"],
        ["Gothic Lolita", "the-loai/gothic-lolita"],
        ["Group", "the-loai/group"],
        ["Guro", "the-loai/guro"],
        ["Hài hước", "the-loai/hai-huoc"],
        ["Hairy", "the-loai/hairy"],
        ["Handjob", "the-loai/handjob"],
        ["Harem", "the-loai/harem"],
        ["Hentai", "the-loai/hentai"],
        ["HentaiVN", "the-loai/hentaivn"],
        ["Hiện đại", "the-loai/hien-dai"],
        ["Historical", "the-loai/historical"],
        ["Horror", "the-loai/horror"],
        ["Housewife", "the-loai/housewife"],
        ["Humiliation", "the-loai/humiliation"],
        ["Idol", "the-loai/idol"],
        ["Imouto", "the-loai/imouto"],
        ["Incest", "the-loai/incest"],
        ["Insect (Côn Trùng)", "the-loai/insect-con-trung"],
        ["Isekai", "the-loai/isekai"],
        ["Không che", "the-loai/khong-che"],
        ["không NTR", "the-loai/khong-ntr"],
        ["Kimono", "the-loai/kimono"],
        ["Kissing", "the-loai/kissing"],
        ["Kuudere", "the-loai/kuudere"],
        ["Lãng Mạn", "the-loai/lang-man"],
        ["Lolicon", "the-loai/lolicon"],
        ["Maids", "the-loai/maids"],
        ["MANGA", "the-loai/manga"],
        ["Manhua", "the-loai/manhua"],
        ["Manhwa", "the-loai/manhwa"],
        ["Masturbation", "the-loai/masturbation"],
        ["Mature", "the-loai/mature"],
        ["Miko", "the-loai/miko"],
        ["Milf", "the-loai/milf"],
        ["Mind Break", "the-loai/mind-break"],
        ["Mind Control", "the-loai/mind-control"],
        ["Mizugi", "the-loai/mizugi"],
        ["Monster", "the-loai/monster"],
        ["Monstergirl", "the-loai/monstergirl"],
        ["Mother", "the-loai/mother"],
        ["Nakadashi", "the-loai/nakadashi"],
        ["Netori", "the-loai/netori"],
        ["Ngôn Tình", "the-loai/ngon-tinh"],
        ["Non-hen", "the-loai/non-hen"],
        ["NTR", "the-loai/ntr"],
        ["Nun", "the-loai/nun"],
        ["Nurse", "the-loai/nurse"],
        ["Old Man", "the-loai/old-man"],
        ["One shot", "the-loai/one-shot"],
        ["Oneshot", "the-loai/oneshot"],
        ["Oral", "the-loai/oral"],
        ["Osananajimi", "the-loai/osananajimi"],
        ["Paizuri", "the-loai/paizuri"],
        ["Pantyhose", "the-loai/pantyhose"],
        ["Ponytail", "the-loai/ponytail"],
        ["Pregnant", "the-loai/pregnant"],
        ["Prostitution", "the-loai/prostitution"],
        ["Rape", "the-loai/rape"],
        ["Rimjob", "the-loai/rimjob"],
        ["Romanc", "the-loai/romanc"],
        ["Romance", "the-loai/romance"],
        ["Ryona", "the-loai/ryona"],
        ["Scat", "the-loai/scat"],
        ["School Uniform", "the-loai/school-uniform"],
        ["SchoolGirl", "the-loai/schoolgirl"],
        ["Series", "the-loai/series"],
        ["Sex Toys", "the-loai/sex-toys"],
        ["Shimapan", "the-loai/shimapan"],
        ["Short Hentai", "the-loai/short-hentai"],
        ["Shota", "the-loai/shota"],
        ["Shoujo", "the-loai/shoujo"],
        ["Siscon", "the-loai/siscon"],
        ["Sister", "the-loai/sister"],
        ["Slave", "the-loai/slave"],
        ["Sleeping", "the-loai/sleeping"],
        ["Small Boobs", "the-loai/small-boobs"],
        ["Smut", "the-loai/smut"],
        ["Son", "the-loai/son"],
        ["Sports", "the-loai/sports"],
        ["Stockings", "the-loai/stockings"],
        ["Supernatural", "the-loai/supernatural"],
        ["Sweating", "the-loai/sweating"],
        ["Swimsuit", "the-loai/swimsuit"],
        ["Tall Girl", "the-loai/tall-girl"],
        ["Teacher", "the-loai/teacher"],
        ["Tentacles", "the-loai/tentacles"],
        ["Time Stop", "the-loai/time-stop"],
        ["Tình Cảm", "the-loai/tinh-cam"],
        ["Tomboy", "the-loai/tomboy"],
        ["Tracksuit", "the-loai/tracksuit"],
        ["Transformation", "the-loai/transformation"],
        ["Trap", "the-loai/trap"],
        ["Truyện Màu", "the-loai/truyen-mau"],
        ["Truyện tranh 18+", "the-loai/truyen-tranh-18"],
        ["Truyện Việt", "the-loai/truyen-viet"],
        ["Tsundere", "the-loai/tsundere"],
        ["Twins", "the-loai/twins"],
        ["Twintails", "the-loai/twintails"],
        ["Vampire", "the-loai/vampire"],
        ["Vanilla", "the-loai/vanilla"],
        ["Vếu to", "the-loai/veu-to"],
        ["Virgin", "the-loai/virgin"],
        ["Webtoon", "the-loai/webtoon"],
        ["X-ray", "the-loai/x-ray"],
        ["Yandere", "the-loai/yandere"],
        ["Yaoi", "the-loai/yaoi"],
        ["Yuri", "the-loai/yuri"],
        ["Zombie", "the-loai/zombie"]
    ];

    var result = [];
    for (var i = 0; i < genres.length; i++) {
        result.push({
            title: genres[i][0],
            input: BASE_URL + "/" + genres[i][1] + "?order_by=update_time&sort=desc",
            script: "genrecontent.js"
        });
    }
    return Response.success(result);
}
